// Generated by Haxe 4.3.7
(function ($global) { "use strict";
Math.__name__ = true;
var Reflect = function() { };
Reflect.__name__ = true;
Reflect.isFunction = function(f) {
	if(typeof(f) == "function") {
		return !(f.__name__ || f.__ename__);
	} else {
		return false;
	}
};
var TestClientSimple = function() { };
TestClientSimple.__name__ = true;
TestClientSimple.main = function() {
	console.log("TestClientSimple.hx:3:","Hello from JavaScript!");
	var f = function() {
		return "test";
	};
	if(Reflect.isFunction(f)) {
		console.log("TestClientSimple.hx:8:","Function check works!");
	}
	var doc = window.document;
	console.log("TestClientSimple.hx:14:","Document title: " + doc.title);
};
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
String.__name__ = true;
Array.__name__ = true;
TestClientSimple.main();
})({});
