package phoenix_chat_hx;

/**
 * Main entry point for Reflaxe.Elixir compilation
 * Generated by mix haxe.gen.project
 */
@:module
class Main {
	public static function main():Void {
		// Entry point for Haxe compilation
		trace("PhoenixChatHx - Reflaxe.Elixir compilation successful!");
	}

	public static function hello(name:String):String {
		return 'Hello, $name! Welcome to Reflaxe.Elixir!';
	}
}
