import assert from "node:assert/strict"
import crypto from "node:crypto"
import fs from "node:fs"
import path from "node:path"
import test from "node:test"
import {fileURLToPath} from "node:url"

const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..")
const tokenPath = path.join(projectRoot, "assets/css/crema-tokens.css")
const appPath = path.join(projectRoot, "assets/css/app.css")
const expectedDigest = "f9e622ab1acae8120dbc1595d6bcadc4a50e2bb0b6657933b26b526f3539ef28"

test("materialized Crema token CSS matches the exact Caf projection", () => {
  const tokenBytes = fs.readFileSync(tokenPath)
  const tokenCss = tokenBytes.toString("utf8")
  const digest = crypto.createHash("sha256").update(tokenBytes).digest("hex")

  assert.equal(digest, expectedDigest)
  assert.match(tokenCss, /@generated by Cafetera from caf:cafetera-crema:design-token-set:field-notes-atelier/)
  assert.match(tokenCss, /These bytes do not prove owner selection/)
  assert.match(tokenCss, /--crema-paper: #f2eee2;/)
  assert.match(tokenCss, /--crema-ink-rgb: 21 36 30;/)
  assert.match(tokenCss, /--crema-motion-entry-duration: 0ms;/)
})

test("native CSS imports semantic values instead of redefining them", () => {
  const appCss = fs.readFileSync(appPath, "utf8")
  assert.match(appCss, /@import "\.\/crema-tokens\.css";/)
  assert.match(appCss, /var\(--crema-motion-entry-duration\)/)
  assert.match(appCss, /var\(--crema-radius-paper\)/)
  assert.match(appCss, /var\(--crema-space-working\)/)

  for (const duplicatedValue of ["#f2eee2", "#15241e", "#d84a2f", "#d7ed72", "#2455c3", "180ms"]) {
    assert.equal(appCss.includes(duplicatedValue), false, `app.css duplicated CML-owned token value ${duplicatedValue}`)
  }
  for (const duplicatedDeclaration of ["--crema-paper:", "--crema-ink:", "--crema-vermilion:", "--crema-citron:", "--crema-cobalt:"]) {
    assert.equal(appCss.includes(duplicatedDeclaration), false, `app.css redefined generated token ${duplicatedDeclaration}`)
  }
})
