defmodule GeneratedOutputOwnershipTest do
  use ExUnit.Case, async: false

  setup do
    unique = System.unique_integer([:positive, :monotonic])
    project = Path.join(System.tmp_dir!(), "generated_output_ownership_#{unique}")
    source = Path.join(project, "src_haxe")
    output = Path.join(project, "lib")

    File.mkdir_p!(source)
    File.mkdir_p!(output)
    HaxeTestHelper.setup_haxe_libraries(project)

    on_exit(fn -> File.rm_rf(project) end)

    {:ok, project: project, source: source, output: output}
  end

  test "publishes deterministic owned updates, legacy upgrades, namespace moves, and safe clean",
       %{
         project: project,
         output: output
       } do
    write_module(project, "one", "release_one")
    write_build(project, "one.Main")
    handwritten = Path.join(output, "handwritten.ex")
    File.write!(handwritten, "defmodule Handwritten do\nend\n")

    files = compile!(project)
    generated = Path.join(output, "one/main.ex")
    manifest_path = HaxeGeneratedOutput.manifest_path(output)
    first_manifest = File.read!(manifest_path)
    first_json = Jason.decode!(first_manifest)

    assert generated in files
    assert first_json["version"] == 2
    assert first_json["protocol"] == "reflaxe-elixir/generated-output"
    assert Enum.any?(first_json["ownedFiles"], &(&1["path"] == "one/main.ex"))
    assert File.read!(generated) =~ "release_one"
    assert File.read!(handwritten) == "defmodule Handwritten do\nend\n"

    fixed_time = {{2020, 1, 1}, {0, 0, 0}}
    File.touch!(generated, fixed_time)
    compile!(project)

    assert File.stat!(generated) |> Map.fetch!(:mtime) == fixed_time
    assert File.read!(manifest_path) == first_manifest

    # A version 1 manifest is the explicit upgrade boundary. It owns its listed
    # files without relying on generated-module comments; the next publish adds
    # content hashes and the version 2 protocol.
    legacy =
      first_json
      |> Map.take(["filesGenerated", "id", "wasCached"])
      |> Map.put("version", 1)

    File.write!(manifest_path, Jason.encode!(legacy, pretty: true) <> "\n")
    write_module(project, "one", "release_two")
    compile!(project)

    assert File.read!(generated) =~ "release_two"
    assert Jason.decode!(File.read!(manifest_path))["version"] == 2

    # Rolling application source back is an ordinary owned update: the manifest
    # follows the older generated bytes without requiring destructive cleanup.
    write_module(project, "one", "release_one")
    compile!(project)
    assert File.read!(generated) =~ "release_one"

    # Moving the Haxe namespace changes the generated target path. The old owned
    # file is stale and must disappear while the unrelated handwritten module stays.
    File.rm_rf!(Path.join([project, "src_haxe", "one"]))
    write_module(project, "two", "release_one")
    write_build(project, "two.Main")
    compile!(project)

    refute File.exists?(generated)
    assert File.read!(Path.join(output, "two/main.ex")) =~ "release_one"
    assert File.exists?(handwritten)

    assert {:ok, cleaned_count} = HaxeGeneratedOutput.clean(output)
    assert cleaned_count > 0
    refute File.exists?(Path.join(output, "two/main.ex"))
    refute File.exists?(manifest_path)
    assert File.read!(handwritten) == "defmodule Handwritten do\nend\n"
  end

  test "rejects a handwritten collision before changing any target file", %{
    project: project,
    output: output
  } do
    write_module(project, nil, "compiler_value")
    write_build(project, "Main")
    collision = Path.join(output, "main.ex")
    neighbor = Path.join(output, "neighbor.ex")
    File.write!(collision, "defmodule Main do\n  def handwritten, do: true\nend\n")
    File.write!(neighbor, "defmodule Neighbor do\nend\n")

    collision_before = File.read!(collision)
    neighbor_before = File.read!(neighbor)

    assert {:error, reason} = compile(project)
    assert reason =~ "Refusing to overwrite unowned file"
    assert File.read!(collision) == collision_before
    assert File.read!(neighbor) == neighbor_before
    refute File.exists?(HaxeGeneratedOutput.manifest_path(output))
    refute File.exists?(Path.join(output, "._GeneratedFiles.prepare"))
    refute File.exists?(Path.join(output, "._GeneratedFiles.transaction"))
  end

  test "rejects modified owned output and clean fails before deleting siblings", %{
    project: project,
    output: output
  } do
    write_module(project, nil, "owned_value")
    write_build(project, "Main")
    compile!(project)

    modified = Path.join(output, "main.ex")

    sibling =
      output
      |> HaxeGeneratedOutput.generated_files()
      |> then(fn {:ok, files} -> Enum.find(files, &(&1 != modified)) end)

    sibling_before = File.read!(sibling)
    File.write!(modified, "defmodule Main do\n  def manually_edited, do: true\nend\n")

    assert {:error, compile_reason} = compile(project)
    assert compile_reason =~ "modified outside the compiler"
    assert File.read!(sibling) == sibling_before

    assert {:error, clean_reason} = HaxeGeneratedOutput.clean(output)
    assert clean_reason =~ "modified outside the compiler"
    assert File.exists?(sibling)
    assert File.read!(modified) =~ "manually_edited"
  end

  test "an interrupted publication rolls back before the next compiler run", %{
    project: project,
    output: output
  } do
    write_module(project, "recoverable", "stable_value")
    write_build(project, "recoverable.Main")
    compile!(project)

    relative = "recoverable/main.ex"
    target = Path.join(output, relative)
    stable_output = File.read!(target)
    manifest_path = HaxeGeneratedOutput.manifest_path(output)
    stable_manifest = File.read!(manifest_path)

    active =
      seed_interrupted_transaction(
        output,
        relative,
        stable_output,
        stable_manifest,
        "partial publication"
      )

    compile!(project)

    assert File.read!(target) == stable_output
    assert File.read!(manifest_path) == stable_manifest
    refute File.exists?(active)
  end

  test "interrupted recovery preserves an unexpected post-crash edit", %{
    project: project,
    output: output
  } do
    write_module(project, "recoverable", "stable_value")
    write_build(project, "recoverable.Main")
    compile!(project)

    relative = "recoverable/main.ex"
    target = Path.join(output, relative)
    stable_output = File.read!(target)
    manifest_path = HaxeGeneratedOutput.manifest_path(output)
    stable_manifest = File.read!(manifest_path)

    active =
      seed_interrupted_transaction(
        output,
        relative,
        stable_output,
        stable_manifest,
        "compiler partial publication"
      )

    File.write!(target, "manual post-crash edit")

    assert {:error, compiler_reason} = compile(project)
    assert compiler_reason =~ "changed after the interrupted publication"
    assert File.read!(target) == "manual post-crash edit"
    assert File.read!(manifest_path) == stable_manifest
    assert File.exists?(active)

    assert {:error, mix_reason} = HaxeGeneratedOutput.recover(output)
    assert mix_reason =~ "changed after the interrupted publication"
    assert File.read!(target) == "manual post-crash edit"
    assert File.read!(manifest_path) == stable_manifest
    assert File.exists?(active)
  end

  test "a symlinked ownership manifest fails before generated files are changed", %{
    project: project,
    output: output
  } do
    write_module(project, nil, "owned_value")
    write_build(project, "Main")
    compile!(project)

    generated = Path.join(output, "main.ex")
    generated_before = File.read!(generated)
    manifest = HaxeGeneratedOutput.manifest_path(output)
    manifest_copy = Path.join(project, "outside-manifest.json")
    File.cp!(manifest, manifest_copy)
    File.rm!(manifest)
    File.ln_s!(manifest_copy, manifest)

    assert {:error, clean_reason} = HaxeGeneratedOutput.clean(output)
    assert clean_reason =~ "manifest is not a regular file (symlink)"
    assert File.read!(generated) == generated_before

    assert {:error, compile_reason} = compile(project)
    assert compile_reason =~ "ownership manifest"
    assert compile_reason =~ "symbolic link"
    assert File.read!(generated) == generated_before
  end

  defp compile!(project) do
    case compile(project) do
      {:ok, files} -> files
      {:error, reason} -> flunk("Haxe compilation failed:\n#{reason}")
    end
  end

  defp compile(project) do
    HaxeCompiler.compile(
      hxml_file: Path.join(project, "build.hxml"),
      source_dir: Path.join(project, "src_haxe"),
      target_dir: Path.join(project, "lib"),
      manifest_path: Path.join(project, "compile.haxe")
    )
  end

  defp write_build(project, main_module) do
    File.write!(
      Path.join(project, "build.hxml"),
      """
      -cp src_haxe
      -lib reflaxe.elixir
      -D elixir_output=lib
      -D reflaxe.dont_output_metadata_id
      #{main_module}
      """
    )
  end

  defp write_module(project, package, value) do
    package_parts = if package, do: String.split(package, "."), else: []
    directory = Path.join([project, "src_haxe" | package_parts])
    File.mkdir_p!(directory)
    package_declaration = if package, do: "package #{package};\n\n", else: ""

    File.write!(
      Path.join(directory, "Main.hx"),
      """
      #{package_declaration}class Main {
        public static function main():Void {
          trace("#{value}");
        }
      }
      """
    )
  end

  defp seed_interrupted_transaction(
         output,
         relative,
         previous_output,
         previous_manifest,
         next_output
       ) do
    active = Path.join(output, "._GeneratedFiles.transaction")
    backups = Path.join(active, "backups")
    File.mkdir_p!(backups)
    File.write!(Path.join(active, "owner"), "reflaxe.elixir generated-output transaction v2\n")
    File.write!(Path.join(backups, "0"), previous_output)
    File.write!(Path.join(active, "previous_manifest.json"), previous_manifest)

    next_manifest = "{\"interrupted\":true}\n"
    File.write!(Path.join(active, "next_manifest.json"), next_manifest)

    journal = %{
      "protocol" => "reflaxe-elixir/generated-output-transaction",
      "version" => 2,
      "paths" => [
        %{
          "path" => relative,
          "tempPath" => relative <> ".__reflaxe_output_new__",
          "hadPrevious" => true,
          "previousDigest" => sha256(previous_output),
          "nextDigest" => sha256(next_output)
        }
      ],
      "previousManifest" => true,
      "previousManifestDigest" => sha256(previous_manifest),
      "nextManifestDigest" => sha256(next_manifest)
    }

    File.write!(Path.join(active, "journal.json"), Jason.encode!(journal, pretty: true) <> "\n")
    File.write!(Path.join(output, relative), next_output)
    active
  end

  defp sha256(content) do
    :crypto.hash(:sha256, content)
    |> Base.encode16(case: :lower)
  end
end
