defmodule HaxePhoenixLiveReactTest do
  use ExUnit.Case, async: true

  @revision "055e80e6a4e6d009df5e229eb39e7f85f03fea22"
  @repository "https://github.com/mrdotb/live_react.git"
  @manifest "phoenixhx-live-react.json"
  @generated_signature "@generated by mix haxe.phoenix.live_react; do not edit"

  test "Genes project at the root applies, checks, recovers generated files, and removes" do
    root = fixture_root(:genes, ".")
    originals = original_sources(root)

    result = HaxePhoenixLiveReact.apply!(root, apply_options(root))

    assert result.package_root == "."
    assert result.client_mode == :genes
    assert result.npm_reference == "file:deps/live_react"
    assert result.dependency["resolvedRevision"] == @revision

    assert File.read!(Path.join(root, "mix.exs")) =~
             "BEGIN reflaxe_elixir live_react_dependency"

    assert File.read!(Path.join(root, "config/dev.exs")) =~
             ~S|vite: ["npm", "run", "assets:dev", cd: Path.expand("../", __DIR__)]|

    assert File.read!(Path.join(root, "assets/js/app.js")) =~
             "Object.assign(Hooks, reactHooks);"

    assert File.read!(root_layout(root)) =~ """
               <%!-- BEGIN reflaxe_elixir live_react_vite_assets --%>
               <LiveReact.Reload.vite_assets assets={["/js/app.js"]}>
                 <script defer phx-track-static type="text/javascript" src={~p"/assets/app.js"}></script>
               </LiveReact.Reload.vite_assets>
               <%!-- END reflaxe_elixir live_react_vite_assets --%>
           """

    assert :live_react in Map.keys(Mix.Dep.Lock.read(Path.join(root, "mix.lock")))
    assert File.read!(Path.join(root, "vite.config.mjs")) =~ @generated_signature

    manifest = File.read!(Path.join(root, @manifest)) |> Jason.decode!()
    assert manifest["components"] == []

    assert get_in(manifest, ["managed", "restores", "mix.lockOriginalState"]) == %{
             "kind" => "empty",
             "content" => "%{}\n"
           }

    assert HaxePhoenixLiveReact.check!(root, rerun_options())[:mode] == :check

    File.rm!(Path.join([root, "assets", "react-components", "registry.generated.js"]))
    HaxePhoenixLiveReact.apply!(root, rerun_options())
    assert File.regular?(Path.join([root, "assets", "react-components", "registry.generated.js"]))

    after_recovery = tree_snapshot(root)
    HaxePhoenixLiveReact.apply!(root, rerun_options())
    assert tree_snapshot(root) == after_recovery

    removed = HaxePhoenixLiveReact.remove!(root, yes: true)

    assert removed.retained_package_keys == []
    refute File.exists?(Path.join(root, @manifest))
    refute File.exists?(Path.join(root, "vite.config.mjs"))
    refute File.exists?(Path.join(root, "assets/js/live-react-hooks.js"))
    refute File.exists?(Path.join([root, "assets", "react-components", "registry.generated.js"]))
    refute :live_react in Map.keys(Mix.Dep.Lock.read(Path.join(root, "mix.lock")))

    assert File.read!(Path.join(root, "assets/js/app.js")) == originals.app_js
    assert File.read!(root_layout(root)) == originals.root_layout
    assert File.read!(Path.join(root, "config/dev.exs")) == originals.dev_exs
    assert File.read!(Path.join(root, "config/config.exs")) == originals.config_exs
    assert File.read!(Path.join(root, "mix.exs")) == originals.mix_exs
    assert File.read!(Path.join(root, "mix.lock")) == originals.mix_lock

    package = Jason.decode!(File.read!(Path.join(root, "package.json")))
    assert package == %{"name" => "demo-assets"}
  end

  test "plain-JS project with an assets package root preserves its existing hook expression" do
    root = fixture_root(:plain_js, "assets")
    original_app_js = File.read!(Path.join(root, "assets/js/app.js"))

    result = HaxePhoenixLiveReact.apply!(root, apply_options(root))

    assert result.package_root == "assets"
    assert result.client_mode == :plain_js
    assert result.npm_reference == "file:../deps/live_react"

    app_js = File.read!(Path.join(root, "assets/js/app.js"))
    assert app_js =~ "window.Hooks = {...(window.Hooks || {}), ...reactHooks}"
    assert app_js =~ "hooks: {...colocatedHooks, ...(window.Hooks || {})},"

    assert File.read!(Path.join(root, "config/dev.exs")) =~
             ~S|vite: ["npm", "run", "assets:dev", cd: Path.expand("../assets", __DIR__)]|

    package = Jason.decode!(File.read!(Path.join(root, "assets/package.json")))
    assert package["dependencies"]["live_react"] == "file:../deps/live_react"

    assert HaxePhoenixLiveReact.check!(root, rerun_options())[:package_root] == "assets"
    HaxePhoenixLiveReact.remove!(root, yes: true)

    assert File.read!(Path.join(root, "assets/js/app.js")) == original_app_js
    refute File.exists?(Path.join(root, @manifest))
  end

  test "check reports drift without changing a byte" do
    root = fixture_root(:genes, ".")
    HaxePhoenixLiveReact.apply!(root, apply_options(root))

    hooks = Path.join(root, "assets/js/live-react-hooks.js")
    File.write!(hooks, String.replace(File.read!(hooks), "reactHooks", "changedHooks"))
    before = tree_snapshot(root)

    assert_raise RuntimeError, ~r/integration drift detected/, fn ->
      HaxePhoenixLiveReact.check!(root, rerun_options())
    end

    assert tree_snapshot(root) == before
  end

  test "an unowned generated path fails before any tracked write" do
    root = fixture_root(:genes, ".")
    File.write!(Path.join(root, "vite.config.mjs"), "export default {}\n")
    before = tree_snapshot(root)

    assert_raise RuntimeError,
                 ~r/exists without the PhoenixHx LiveReact ownership signature/,
                 fn ->
                   HaxePhoenixLiveReact.apply!(root, apply_options(root))
                 end

    assert tree_snapshot(root) == before
  end

  test "a conflicting package key fails before any tracked write" do
    root = fixture_root(:genes, ".")
    package_path = Path.join(root, "package.json")
    File.write!(package_path, ~s({"name":"demo-assets","scripts":{"assets:build":"custom"}}\n))
    before = tree_snapshot(root)

    assert_raise RuntimeError, ~r/scripts.assets:build conflicts/, fn ->
      HaxePhoenixLiveReact.apply!(root, apply_options(root))
    end

    assert tree_snapshot(root) == before
  end

  test "package-root traversal is rejected before any tracked write" do
    root = fixture_root(:genes, ".")
    before = tree_snapshot(root)

    assert_raise RuntimeError, ~r/project-relative|parent traversal/, fn ->
      root
      |> HaxePhoenixLiveReact.apply!(Keyword.put(apply_options(root), :package_root, "../assets"))
    end

    assert tree_snapshot(root) == before
  end

  test "malformed ownership markers fail before any tracked write" do
    root = fixture_root(:genes, ".")
    config = Path.join(root, "config/config.exs")
    File.write!(config, File.read!(config) <> "# BEGIN reflaxe_elixir live_react_config\n")
    before = tree_snapshot(root)

    assert_raise RuntimeError, ~r/malformed or overlapping ownership markers/, fn ->
      HaxePhoenixLiveReact.apply!(root, apply_options(root))
    end

    assert tree_snapshot(root) == before
  end

  test "dependency resolution may only change the LiveReact lock entry" do
    root = fixture_root(:genes, ".")
    before = tree_snapshot(root)

    options =
      apply_options(root,
        lock_content:
          lock_content(%{
            live_react: git_lock(),
            phoenix: {:hex, :phoenix, "99.0.0", "00", [], [], "hexpm", "00"}
          })
      )

    assert_raise RuntimeError, ~r/changed lock entries unrelated to :live_react/, fn ->
      HaxePhoenixLiveReact.apply!(root, options)
    end

    assert tree_snapshot(root) == before
  end

  test "removal deletes a task-created lockfile and preserves unrelated later lock entries" do
    root = fixture_root(:genes, ".")
    lock_path = Path.join(root, "mix.lock")
    File.rm!(lock_path)

    HaxePhoenixLiveReact.apply!(root, apply_options(root))
    assert File.regular?(lock_path)

    File.write!(
      lock_path,
      lock_content(%{
        live_react: git_lock(),
        phoenix: {:hex, :phoenix, "1.7.24", "00", [], [], "hexpm", "00"}
      })
    )

    HaxePhoenixLiveReact.remove!(root, yes: true)

    retained = Mix.Dep.Lock.read(lock_path)
    assert Map.has_key?(retained, :phoenix)
    refute Map.has_key?(retained, :live_react)

    second_root = fixture_root(:genes, ".")
    second_lock = Path.join(second_root, "mix.lock")
    File.rm!(second_lock)

    HaxePhoenixLiveReact.apply!(second_root, apply_options(second_root))
    HaxePhoenixLiveReact.remove!(second_root, yes: true)
    refute File.exists?(second_lock)
  end

  test "a populated lockfile round-trips byte-for-byte" do
    root = fixture_root(:genes, ".")
    lock_path = Path.join(root, "mix.lock")

    phoenix_lock = {:hex, :phoenix, "1.7.24", "00", [], [], "hexpm", "00"}
    original = lock_content(%{phoenix: phoenix_lock})
    File.write!(lock_path, original)

    HaxePhoenixLiveReact.apply!(
      root,
      apply_options(root,
        lock_content: lock_content(%{live_react: git_lock(), phoenix: phoenix_lock})
      )
    )

    HaxePhoenixLiveReact.remove!(root, yes: true)
    assert File.read!(lock_path) == original
  end

  test "a checkout revision mismatch is rejected before planning writes" do
    root = fixture_root(:genes, ".")
    before = tree_snapshot(root)

    options =
      apply_options(root,
        git_revision: fn _checkout -> String.duplicate("a", 40) end
      )

    assert_raise RuntimeError, ~r/checkout HEAD does not match mix.lock/, fn ->
      HaxePhoenixLiveReact.apply!(root, options)
    end

    assert tree_snapshot(root) == before
  end

  test "removal rejects edits inside an owned marker and leaves the tree unchanged" do
    root = fixture_root(:genes, ".")
    HaxePhoenixLiveReact.apply!(root, apply_options(root))

    config = Path.join(root, "config/config.exs")

    File.write!(
      config,
      String.replace(File.read!(config), "ssr: false", "ssr: true", global: false)
    )

    before = tree_snapshot(root)

    assert_raise RuntimeError, ~r/content drifted inside its ownership markers/, fn ->
      HaxePhoenixLiveReact.remove!(root, yes: true)
    end

    assert tree_snapshot(root) == before
  end

  test "removal retains package keys imported by hand-owned browser source" do
    root = fixture_root(:plain_js, "assets")
    HaxePhoenixLiveReact.apply!(root, apply_options(root))

    custom = Path.join([root, "assets", "react-components", "custom.tsx"])

    File.write!(custom, """
    import React from "react"
    import {createRoot} from "react-dom/client"
    import {getHooks} from "live_react"

    export const retained = [React, createRoot, getHooks]
    """)

    result = HaxePhoenixLiveReact.remove!(root, yes: true)
    package = Jason.decode!(File.read!(Path.join(root, "assets/package.json")))

    assert result.retained_package_keys == [
             "dependencies.live_react",
             "dependencies.react",
             "dependencies.react-dom"
           ]

    assert result.retained_live_react_dependency

    assert package["dependencies"]["live_react"] == "file:../deps/live_react"
    assert package["dependencies"]["react"] == "19.1.0"
    assert package["dependencies"]["react-dom"] == "19.1.0"
    assert File.regular?(custom)
    assert File.read!(Path.join(root, "mix.exs")) =~ "{:live_react,"
    refute File.read!(Path.join(root, "mix.exs")) =~ "live_react_dependency"
    assert :live_react in Map.keys(Mix.Dep.Lock.read(Path.join(root, "mix.lock")))
  end

  test "a hand-owned project-relative LiveReact path remains the runtime owner" do
    root = fixture_root(:plain_js, "assets")
    File.mkdir_p!(Path.join(root, "vendor"))
    File.cp_r!(Path.join(root, "deps/live_react"), Path.join(root, "vendor/live_react"))

    mix_path = Path.join(root, "mix.exs")

    File.write!(
      mix_path,
      String.replace(
        File.read!(mix_path),
        "defp deps do\n    []",
        "defp deps do\n    [{:live_react, path: \"vendor/live_react\"}]"
      )
    )

    result =
      HaxePhoenixLiveReact.apply!(root,
        yes: true,
        mix_dependencies: [{:live_react, path: "vendor/live_react"}]
      )

    assert result.dependency["sourceKind"] == "path"
    assert result.npm_reference == "file:../vendor/live_react"
    refute File.read!(mix_path) =~ "live_react_dependency"

    HaxePhoenixLiveReact.remove!(root, yes: true)

    assert File.read!(mix_path) =~ ~s({:live_react, path: "vendor/live_react"})
    refute File.exists?(Path.join(root, @manifest))
  end

  test "inline plain-JS hooks fail closed instead of producing invalid JavaScript" do
    root = fixture_root(:plain_js, ".")
    app_js = Path.join(root, "assets/js/app.js")

    File.write!(app_js, """
    import "phoenix_html"
    import {Socket} from "phoenix"
    import {LiveSocket} from "phoenix_live_view"

    const liveSocket = new LiveSocket("/live", Socket, {hooks: {}})
    liveSocket.connect()
    """)

    before = tree_snapshot(root)

    assert_raise RuntimeError, ~r/inline LiveSocket hooks property/, fn ->
      HaxePhoenixLiveReact.apply!(root, apply_options(root))
    end

    assert tree_snapshot(root) == before
  end

  test "the public Mix task applies, checks, and removes in an external project" do
    root = fixture_root(:plain_js, "assets")
    repository_root = Path.expand("../..", __DIR__)
    File.mkdir_p!(Path.join(root, "vendor"))
    File.cp_r!(Path.join(root, "deps/live_react"), Path.join(root, "vendor/live_react"))

    mix_path = Path.join(root, "mix.exs")

    File.write!(
      mix_path,
      String.replace(
        File.read!(mix_path),
        "defp deps do\n    []",
        """
        defp deps do
            [
              {:jason, path: #{inspect(Path.join(repository_root, "deps/jason"))}, override: true},
              {:reflaxe_elixir, path: #{inspect(repository_root)}},
              {:live_react, path: "vendor/live_react"}
            ]
        """
        |> String.trim_trailing()
      )
    )

    Enum.each(["mix.exs", "config/config.exs", "config/dev.exs"], fn relative ->
      path = Path.join(root, relative)
      formatted = path |> File.read!() |> Code.format_string!() |> IO.iodata_to_binary()
      File.write!(path, formatted <> "\n")
    end)

    run_external_mix!(root, ["deps.get"])
    run_external_mix!(root, ["deps.compile", "reflaxe_elixir"])

    apply_output = run_live_react_task!(root, ["--yes"])
    assert apply_output =~ "PhoenixHx LiveReact integration is current"
    assert apply_output =~ "path:vendor/live_react@0.1.0"

    run_external_mix!(root, [
      "format",
      "--check-formatted",
      "mix.exs",
      "config/config.exs",
      "config/dev.exs"
    ])

    Enum.each(
      [
        "assets/js/app.js",
        "assets/js/live-react-hooks.js",
        "assets/react-components/registry.generated.js",
        "assets/vite.config.mjs"
      ],
      &run_node_syntax_check!(root, &1)
    )

    check_output = run_live_react_task!(root, ["--check"])
    assert check_output =~ "check passed; no writes occurred"

    remove_output = run_live_react_task!(root, ["--remove", "--yes"])
    assert remove_output =~ "Removed all currently owned PhoenixHx LiveReact state"
    refute File.exists?(Path.join(root, @manifest))
    assert File.read!(mix_path) =~ ~s({:live_react, path: "vendor/live_react"})
  end

  defp fixture_root(client_mode, package_root) do
    root =
      Path.join(
        System.tmp_dir!(),
        "reflaxe_live_react_#{client_mode}_#{System.unique_integer([:positive, :monotonic])}"
      )

    on_exit(fn -> File.rm_rf!(root) end)

    write!(root, "mix.exs", mix_exs())
    write!(root, "mix.lock", "%{}\n")
    write!(root, "config/config.exs", "import Config\n\nconfig :demo, ecto_repos: []\n")
    write!(root, "config/dev.exs", dev_exs())
    write!(root, "assets/js/app.js", app_js(client_mode))
    write!(root, "lib/demo_web/components/layouts/root.html.heex", root_layout_source())
    write!(root, Path.join(package_root, "package.json"), ~s({"name":"demo-assets"}\n))
    write!(root, "deps/live_react/package.json", ~s({"name":"live_react","version":"0.1.0"}\n))

    write!(root, "deps/live_react/mix.exs", """
    defmodule LiveReact.MixProject do
      use Mix.Project

      def project, do: [app: :live_react, version: "0.1.0"]
      def application, do: []
    end
    """)

    if client_mode == :genes do
      write!(root, "build-client.hxml", "-lib genes\n")
      write!(root, "src_haxe/client/Boot.hx", "package client; class Boot {}\n")
      write!(root, "haxe_libraries/genes.hxml", "-cp vendor/genes/src\n")
    end

    root
  end

  defp apply_options(root, overrides \\ []) do
    lock_content = Keyword.get(overrides, :lock_content, lock_content(%{live_react: git_lock()}))
    revision_reader = Keyword.get(overrides, :git_revision, fn _checkout -> @revision end)

    [
      yes: true,
      mix_dependencies: [],
      git_revision: revision_reader,
      dependency_resolver: fn _context ->
        %{
          lock_content: lock_content,
          dependency_path: Path.join([root, "deps", "live_react"])
        }
      end
    ]
  end

  defp rerun_options do
    [
      yes: true,
      mix_dependencies: [
        {:live_react, [ref: @revision, git: @repository]}
      ],
      git_revision: fn _checkout -> @revision end
    ]
  end

  defp git_lock, do: {:git, @repository, @revision, [ref: @revision]}

  defp lock_content(entries) do
    body =
      entries
      |> Enum.sort_by(fn {name, _entry} -> to_string(name) end)
      |> Enum.map_join(fn {name, entry} -> "  \"#{name}\": #{inspect(entry)},\n" end)

    "%{\n" <> body <> "}\n"
  end

  defp mix_exs do
    """
    defmodule Demo.MixProject do
      use Mix.Project

      def project do
        [app: :demo, version: "0.1.0", deps: deps(), aliases: aliases()]
      end

      def application, do: [extra_applications: [:logger]]

      defp deps do
        []
      end

      defp aliases do
        [
          "assets.setup": ["esbuild.install --if-missing"],
          "assets.build": ["esbuild demo"],
          "assets.deploy": ["esbuild demo --minify", "phx.digest"]
        ]
      end
    end
    """
  end

  defp dev_exs do
    """
    import Config

    config :demo, DemoWeb.Endpoint,
      http: [ip: {127, 0, 0, 1}, port: 4000],
      watchers: [
        esbuild: {Esbuild, :install_and_run, [:demo, ~w(--sourcemap=inline --watch)]},
        tailwind: {Tailwind, :install_and_run, [:demo, ~w(--watch)]}
      ]
    """
  end

  defp app_js(:genes) do
    """
    import "phoenix_html"
    import {Socket} from "phoenix"
    import {LiveSocket} from "phoenix_live_view"

    let Hooks = {};
    const liveSocket = new LiveSocket("/live", Socket, {hooks: Hooks})
    liveSocket.connect()
    """
  end

  defp app_js(:plain_js) do
    """
    import "phoenix_html"
    import {Socket} from "phoenix"
    import {LiveSocket} from "phoenix_live_view"
    import {hooks as colocatedHooks} from "phoenix-colocated/demo"

    const liveSocket = new LiveSocket("/live", Socket, {
      params: {_csrf_token: "test"},
      hooks: {...colocatedHooks},
    })

    liveSocket.connect()
    """
  end

  defp root_layout_source do
    """
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <script defer phx-track-static type="text/javascript" src={~p"/assets/app.js"}></script>
      </head>
      <body>{@inner_content}</body>
    </html>
    """
  end

  defp root_layout(root),
    do: Path.join(root, "lib/demo_web/components/layouts/root.html.heex")

  defp original_sources(root) do
    %{
      app_js: File.read!(Path.join(root, "assets/js/app.js")),
      config_exs: File.read!(Path.join(root, "config/config.exs")),
      dev_exs: File.read!(Path.join(root, "config/dev.exs")),
      mix_exs: File.read!(Path.join(root, "mix.exs")),
      mix_lock: File.read!(Path.join(root, "mix.lock")),
      root_layout: File.read!(root_layout(root))
    }
  end

  defp write!(root, relative, content) do
    path = Path.join(root, relative)
    File.mkdir_p!(Path.dirname(path))
    File.write!(path, content)
  end

  defp tree_snapshot(root) do
    root
    |> Path.join("**/*")
    |> Path.wildcard(match_dot: true)
    |> Enum.filter(&File.regular?/1)
    |> Map.new(fn path -> {Path.relative_to(path, root), File.read!(path)} end)
  end

  defp run_live_react_task!(root, arguments) do
    run_external_mix!(root, ["haxe.phoenix.live_react" | arguments])
  end

  defp run_external_mix!(root, arguments) do
    repository_root = Path.expand("../..", __DIR__)
    timeout = Path.join(repository_root, "scripts/with-timeout.sh")

    {output, status} =
      System.cmd(
        timeout,
        ["--secs", "60", "--", "mix" | arguments],
        cd: root,
        env: [{"MIX_ENV", "prod"}],
        stderr_to_stdout: true
      )

    if status != 0 do
      flunk("LiveReact Mix task failed with status #{status}:\n#{output}")
    end

    output
  end

  defp run_node_syntax_check!(root, relative) do
    repository_root = Path.expand("../..", __DIR__)
    timeout = Path.join(repository_root, "scripts/with-timeout.sh")

    {output, status} =
      System.cmd(
        timeout,
        ["--secs", "30", "--", "node", "--check", relative],
        cd: root,
        stderr_to_stdout: true
      )

    if status != 0 do
      flunk("generated JavaScript syntax check failed for #{relative}:\n#{output}")
    end
  end
end

defmodule Mix.Tasks.Haxe.Phoenix.LiveReactTest do
  use ExUnit.Case, async: false

  test "SSR and conflicting modes are rejected before project discovery" do
    assert_raise RuntimeError, ~r/--ssr is not supported/, fn ->
      Mix.Tasks.Haxe.Phoenix.LiveReact.run(["--ssr"])
    end

    assert_raise RuntimeError, ~r/mutually exclusive/, fn ->
      Mix.Tasks.Haxe.Phoenix.LiveReact.run(["--check", "--remove"])
    end
  end
end
