package reflaxe.elixir.runtime;

import elixir.types.Term;

/**
 * HaxeThrow
 *
 * WHAT
 * - Stable wrapper exception used to implement Haxe `throw` semantics on the BEAM.
 *
 * WHY
 * - The compiler uses Elixir `raise`/`rescue` for Haxe `throw`/`try/catch` so:
 *   - Haxe try/catch does not accidentally intercept internal loop-control `throw(:break|:continue)`.
 *   - Elixir/Phoenix libraries that use exceptions integrate naturally (they raise; Haxe can rescue).
 * - Haxe allows throwing any value (strings, ints, maps, structs). Elixir `raise` expects an exception,
 *   so we wrap non-exception values in a predictable exception struct with a `value` field.
 *
 * HOW
 * - The compiler emits `raise Reflaxe.Elixir.HaxeThrow, message: inspect(value), value: value`.
 * - Haxe try/catch rescues exceptions, unwraps `value` when the exception is HaxeThrow,
 *   then type-matches the thrown value against Haxe catch types.
 *
 * EXAMPLES
 * Haxe:
 *   try {
 *     throw "oops";
 *   } catch (e:String) {
 *     trace(e);
 *   }
 *
 * Elixir (shape):
 *   try do
 *     raise Reflaxe.Elixir.HaxeThrow, message: inspect("oops"), value: "oops"
 *   rescue
 *     __haxe_exception ->
 *       __haxe_thrown_value =
 *         case __haxe_exception do
 *           %Reflaxe.Elixir.HaxeThrow{value: v} -> v
 *           _ -> __haxe_exception
 *         end
 *       case __haxe_thrown_value do
 *         e when is_binary(e) -> ...
 *         _ -> reraise(__haxe_exception, __STACKTRACE__)
 *       end
 *   end
 */
@:native("Reflaxe.Elixir.HaxeThrow")
class HaxeThrow extends haxe.Exception {
	public var value:Term;

	public function new(message:String, ?previous:haxe.Exception, ?native:Any) {
		super(message, previous, native);
	}

	/**
	 * Override `exception/1` generated by `defexception` so the message is useful by default.
	 *
	 * When callers `raise Reflaxe.Elixir.HaxeThrow, value: term` we set `message` to `inspect(term)`
	 * unless a `message:` is explicitly provided.
	 */
	@:native("exception")
	public static function exception(opts:Term):Term {
		return untyped __elixir__('
value = Keyword.get({0}, :value)
message = Keyword.get({0}, :message)
message = if message == nil, do: inspect(value), else: message
struct(__MODULE__, Keyword.put({0}, :message, message))
', opts);
	}
}
