#!/bin/bash

# Fix Test Infrastructure Naming Convention Issues
# Converts PascalCase .ex files in intended directories to snake_case
# Generated by Claude Code on 2025-01-22

set -e  # Exit on any error

echo "🔧 Fixing Test Infrastructure Naming Convention Issues"
echo "Converting PascalCase .ex files to snake_case in intended directories..."

# Function to convert PascalCase to snake_case
pascal_to_snake() {
    echo "$1" | sed 's/\([A-Z]\)/_\1/g' | sed 's/^_//' | tr '[:upper:]' '[:lower:]'
}

# Count total files to process
total_files=$(find test/tests -path "*/intended/*" -name "*.ex" | grep -E "/[A-Z][^/]*\.ex$" | wc -l)
echo "📊 Found $total_files PascalCase .ex files to rename"

# Initialize counters
renamed_count=0
skipped_count=0
errors=()

# Process each PascalCase .ex file
while IFS= read -r filepath; do
    if [[ -z "$filepath" ]]; then
        continue
    fi
    
    # Extract directory and filename
    dir=$(dirname "$filepath")
    filename=$(basename "$filepath")
    
    # Convert filename to snake_case
    snake_filename=$(pascal_to_snake "$filename")
    
    # Skip if already snake_case (shouldn't happen but safety check)
    if [[ "$filename" == "$snake_filename" ]]; then
        echo "⏭️  Skipping already snake_case: $filename"
        ((skipped_count++))
        continue
    fi
    
    new_filepath="$dir/$snake_filename"
    
    # Check if target file already exists
    if [[ -f "$new_filepath" ]]; then
        echo "⚠️  Target exists, skipping: $filename → $snake_filename"
        errors+=("Target file already exists: $new_filepath")
        ((skipped_count++))
        continue
    fi
    
    # Rename the file
    if mv "$filepath" "$new_filepath"; then
        echo "✅ Renamed: $filename → $snake_filename"
        ((renamed_count++))
    else
        echo "❌ Failed to rename: $filename"
        errors+=("Failed to rename: $filepath")
    fi
done < <(find test/tests -path "*/intended/*" -name "*.ex" | grep -E "/[A-Z][^/]*\.ex$")

echo ""
echo "📈 Renaming Summary:"
echo "   ✅ Successfully renamed: $renamed_count files"
echo "   ⏭️  Skipped: $skipped_count files"
echo "   ❌ Errors: ${#errors[@]} files"

if [[ ${#errors[@]} -gt 0 ]]; then
    echo ""
    echo "🚨 Errors encountered:"
    for error in "${errors[@]}"; do
        echo "   - $error"
    done
fi

echo ""
echo "🔄 Next: Update _GeneratedFiles.json files to match new filenames"
echo "Run: ./update_generated_files.sh"