/* Generated by PhoenixHx LiveReactEventProtocol. Do not edit. */
export const LIVE_EVENT_PROTOCOL_HASH = "b2eeed2e8bfa8044415a4d9f6a6f889244aecc25" as const
export const LIVE_EVENT_PROTOCOL_MANIFEST = "protocol StatusPanelEvent\ncompanion StatusPanelEvents\nevent hook Action status_panel_action (payload:StatusPanelActionInput{density:String->density:string;enabled:Bool->enabled:bool;indexes:Array<Int>->indexes:int_array;note:Null<String>->note:string?;progress:Float->progress:float;selectedIndex:Int->selected_index:int;tags:Array<String>->tags:string_array})\nevent hook Ping ping ()\n" as const

/** Structural subset accepted by stock LiveReact's broader pushEvent function. */
export type LiveReactPushEvent = (
  event: string,
  payload: Record<string, unknown>,
) => unknown

const hasOwn = (value: Record<string, unknown>, key: string): boolean =>
  Object.prototype.hasOwnProperty.call(value, key)

function expectRecord(value: unknown, label: string): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(label + " must be an object")
  }
  return value as Record<string, unknown>
}

function expectExactKeys(
  value: Record<string, unknown>,
  required: readonly string[],
  optional: readonly string[],
  label: string,
): void {
  const allowed = new Set([...required, ...optional])
  for (const key of Object.keys(value)) {
    if (!allowed.has(key)) {
      throw new Error(label + " has unexpected field " + key)
    }
  }
  for (const key of required) {
    if (!hasOwn(value, key)) {
      throw new Error(label + " is missing field " + key)
    }
  }
}

function expectString(value: unknown, label: string): string {
  if (typeof value !== "string") {
    throw new Error(label + " must be a string")
  }
  return value
}

function expectInteger(value: unknown, label: string): number {
  if (!Number.isInteger(value)) {
    throw new Error(label + " must be an integer")
  }
  return value as number
}

function expectBoolean(value: unknown, label: string): boolean {
  if (typeof value !== "boolean") {
    throw new Error(label + " must be a boolean")
  }
  return value
}

function expectNumber(value: unknown, label: string): number {
  if (typeof value !== "number") {
    throw new Error(label + " must be a number")
  }
  return value
}

function expectStringArray(value: unknown, label: string): string[] {
  if (!Array.isArray(value) || !value.every((item: unknown) => typeof item === "string")) {
    throw new Error(label + " must be an array of strings")
  }
  return value as string[]
}

function expectIntegerArray(value: unknown, label: string): number[] {
  if (!Array.isArray(value) || !value.every((item: unknown) => Number.isInteger(item))) {
    throw new Error(label + " must be an array of integers")
  }
  return value as number[]
}

export const ACTION_EVENT = "status_panel_action" as const
export interface ActionInput {
  readonly density: string
  readonly enabled: boolean
  readonly indexes: number[]
  readonly note?: string | null
  readonly progress: number
  readonly selectedIndex: number
  readonly tags: string[]
}

export function decodeActionInput(value: unknown): ActionInput {
  const input = expectRecord(value, "StatusPanelEvent.Action")
  expectExactKeys(
    input,
    ["density", "enabled", "indexes", "progress", "selectedIndex", "tags"],
    ["note"],
    "StatusPanelEvent.Action",
  )
  return {
    density: expectString(input["density"], "StatusPanelEvent.Action.density"),
    enabled: expectBoolean(input["enabled"], "StatusPanelEvent.Action.enabled"),
    indexes: expectIntegerArray(input["indexes"], "StatusPanelEvent.Action.indexes"),
    ...(hasOwn(input, "note")
      ? {
          note:
            input["note"] === null
              ? null
              : expectString(input["note"], "StatusPanelEvent.Action.note"),
        }
      : {}),
    progress: expectNumber(input["progress"], "StatusPanelEvent.Action.progress"),
    selectedIndex: expectInteger(input["selectedIndex"], "StatusPanelEvent.Action.selectedIndex"),
    tags: expectStringArray(input["tags"], "StatusPanelEvent.Action.tags"),
  }
}

export function encodeActionPayload(input: ActionInput): Record<string, unknown> {
  return {
    density: input.density,
    enabled: input.enabled,
    indexes: input.indexes,
    ...(input.note === undefined ? {} : {note: input.note}),
    progress: input.progress,
    selected_index: input.selectedIndex,
    tags: input.tags,
  }
}

export function pushAction(pushEvent: LiveReactPushEvent, candidate: ActionInput): void {
  const input = decodeActionInput(candidate)
  pushEvent(ACTION_EVENT, encodeActionPayload(input))
}

export const PING_EVENT = "ping" as const
export type PingInput = Readonly<Record<string, never>>

export function decodePingInput(value: unknown): PingInput {
  const input = expectRecord(value, "StatusPanelEvent.Ping")
  expectExactKeys(
    input,
    [],
    [],
    "StatusPanelEvent.Ping",
  )
  return {}
}

export function encodePingPayload(): Record<string, unknown> {
  return {}
}

export function pushPing(pushEvent: LiveReactPushEvent): void {
  pushEvent(PING_EVENT, encodePingPayload())
}
