package server.schemas;

/**
 * Todo schema for task management
 *
 * Provides the core todo model with priority, due dates, and tags.
 * Supports user association for multi-user todo lists.
 *
 * Uses @:changeset annotation for auto-generated Ecto changeset.
 * The annotation generates proper cast/3 and validate_required/2 calls.
 */
typedef TodoParams = {
    ?title: String,
    ?description: String,
    ?completed: Bool,
    ?priority: String,
    ?dueDate: String,
    ?tags: Array<String>,
    ?userId: Int
}

@:native("TodoApp.Todo")
@:schema("todos")
@:timestamps
@:changeset(["title", "description", "completed", "priority", "dueDate", "tags", "userId"], ["title"])
class Todo {
    @:field @:primary_key public var id: Int;
    @:field public var title: String;
    @:field public var description: String;
    @:field public var completed: Bool = false;
    @:field public var priority: String = "medium";
    @:field public var dueDate: String;
    @:field public var tags: Array<String>;
    @:field public var userId: Int;

    public function new() {
        this.completed = false;
        this.priority = "medium";
    }

    /**
     * Standard changeset for creating and updating todos.
     * Auto-generated by the schema transformer - this extern declaration
     * makes the method available to Haxe code without generating a body.
     */
    extern public static function changeset(todo: Todo, params: TodoParams): Dynamic;

    /**
     * Toggle the completed status of a todo.
     * Returns a changeset with the toggled completed value.
     */
    public static function toggleCompleted(todo: Todo): Dynamic {
        var newCompleted = !todo.completed;
        return ecto.Changeset.change(todo, {completed: newCompleted});
    }

    /**
     * Update the priority of a todo.
     * Returns a changeset with the new priority.
     */
    public static function updatePriority(todo: Todo, priority: String): Dynamic {
        return ecto.Changeset.change(todo, {priority: priority});
    }

    /**
     * Create a new todo with default values
     */
    public static function createNew(title: String, ?userId: Int): TodoParams {
        return {
            title: title,
            description: "",
            completed: false,
            priority: "medium",
            dueDate: null,
            tags: [],
            userId: userId
        };
    }
}
