ExUnit.start()

# BEGIN reflaxe_elixir haxe_exunit_require
# Require Haxe-compiled ExUnit scripts generated by `haxe build-tests.hxml`.
for file <- Path.wildcard("test/generated/**/*_test.exs") do
  Code.require_file(file)
end

# END reflaxe_elixir haxe_exunit_require
