// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); },$hxEnums = $hxEnums || {},$_;
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var ProfileHookEvent = $hxEnums["ProfileHookEvent"] = { __ename__:true,__constructs__:null
	,ClipboardCopied: ($_=function(payload) { return {_hx_index:0,payload:payload,__enum__:"ProfileHookEvent",toString:$estr}; },$_._hx_name="ClipboardCopied",$_.__params__ = ["payload"],$_)
	,Ping: {_hx_name:"Ping",_hx_index:1,__enum__:"ProfileHookEvent",toString:$estr}
};
ProfileHookEvent.__constructs__ = [ProfileHookEvent.ClipboardCopied,ProfileHookEvent.Ping];
var Main = function() { };
Main.__name__ = true;
Main.main = function() {
	var pushed = [];
	var hook = { el : null, pushEvent : function(event,payload) {
		var message = payload["message"];
		var copiedAt = payload["copied_at"];
		pushed.push(event + ":" + message + ":" + copiedAt);
	}};
	var payload = { message : "Copied.", copiedAt : "2026-06-28T16:00:00Z"};
	ProfileHookEvents.pushClipboardCopied(hook,payload);
	ProfileHookEvents.push(hook,ProfileHookEvent.ClipboardCopied(payload));
	ProfileHookEvents.pushPing(hook);
	if(pushed.length != 3) {
		throw haxe_Exception.thrown("expected three pushed events");
	}
};
Math.__name__ = true;
var ProfileHookEvents = function() { };
ProfileHookEvents.__name__ = true;
ProfileHookEvents.encode = function(event) {
	switch(event._hx_index) {
	case 0:
		var payload = event.payload;
		return { event : "clipboard_copied", payload : { copied_at : payload.copiedAt, message : payload.message}};
	case 1:
		return { event : "ping", payload : { }};
	}
};
ProfileHookEvents.decode = function(eventName,payload) {
	if(eventName == "clipboard_copied") {
		var copiedAtRaw = (payload == null ? null : payload["copied_at"]);
		var copiedAt = (typeof copiedAtRaw === 'string' ? copiedAtRaw : null);
		var messageRaw = (payload == null ? null : payload["message"]);
		var message = (typeof messageRaw === 'string' ? messageRaw : null);
		if(copiedAt != null && message != null) {
			return ProfileHookEvent.ClipboardCopied({ copiedAt : copiedAt, message : message});
		} else {
			return null;
		}
	}
	if(eventName == "ping") {
		return ProfileHookEvent.Ping;
	}
	return null;
};
ProfileHookEvents.push = function(hook,event) {
	var encoded = ProfileHookEvents.encode(event);
	if(hook.pushEvent != null) {
		hook.pushEvent(encoded.event,encoded.payload);
	}
};
ProfileHookEvents.pushClipboardCopied = function(hook,payload) {
	if(hook.pushEvent != null) {
		hook.pushEvent("clipboard_copied",{ copied_at : payload.copiedAt, message : payload.message});
	}
};
ProfileHookEvents.pushPing = function(hook) {
	if(hook.pushEvent != null) {
		hook.pushEvent("ping",{ });
	}
};
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.__name__ = true;
haxe_Exception.thrown = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value.get_native();
	} else if(((value) instanceof Error)) {
		return value;
	} else {
		var e = new haxe_ValueException(value);
		return e;
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	get_native: function() {
		return this.__nativeException;
	}
});
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__name__ = true;
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
});
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o.__enum__) {
			var e = $hxEnums[o.__enum__];
			var con = e.__constructs__[o._hx_index];
			var n = con._hx_name;
			if(con.__params__) {
				s = s + "\t";
				return n + "(" + ((function($this) {
					var $r;
					var _g = [];
					{
						var _g1 = 0;
						var _g2 = con.__params__;
						while(true) {
							if(!(_g1 < _g2.length)) {
								break;
							}
							var p = _g2[_g1];
							_g1 = _g1 + 1;
							_g.push(js_Boot.__string_rec(o[p],s));
						}
					}
					$r = _g;
					return $r;
				}(this))).join(",") + ")";
			} else {
				return n;
			}
		}
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var phoenix_live_$view_LiveEventProtocolCompanion = function() { };
phoenix_live_$view_LiveEventProtocolCompanion.__name__ = true;
String.__name__ = true;
Array.__name__ = true;
js_Boot.__toStr = ({ }).toString;
ProfileHookEvents.ClipboardCopiedEvent = "clipboard_copied";
ProfileHookEvents.PingEvent = "ping";
Main.main();
})({});
