package phoenix_live_react_tooling;

import elixir.Enum;
import elixir.Kernel;
import elixir.types.Atom;

typedef Compatibility = {
	repository:String,
	revision:String,
	react:String,
	react_dom:String,
	vite:String
}

/**
 * Deterministic PhoenixHx LiveReact lifecycle values and renderers.
 *
 * This module deliberately has no filesystem, Mix, shell, or prompting access. Typed sibling
 * modules own those host interactions through faithful Elixir externs, while this class keeps
 * deterministic policy and rendering separate. The only handwritten shell is the bounded
 * bootstrap driver that regenerates the checked-in Elixir artifacts.
 */
@:keep
@:native("HaxePhoenixLiveReact.Core")
class IntegrationCore {
	static inline final APPLY:Atom = "apply";
	static inline final GENES:Atom = "genes";

	public static inline final SCHEMA = "phoenixhx.live-react@1";
	public static inline final GENERATED_BY = "mix haxe.phoenix.live_react";
	public static inline final GENERATED_SIGNATURE = "@generated by mix haxe.phoenix.live_react; do not edit";
	public static inline final MANIFEST_FILENAME = "phoenixhx-live-react.json";
	public static inline final LIVE_REACT_REPOSITORY = "https://github.com/mrdotb/live_react.git";
	public static inline final LIVE_REACT_REVISION = "055e80e6a4e6d009df5e229eb39e7f85f03fea22";

	public static function schema():String {
		return SCHEMA;
	}

	public static function generatedBy():String {
		return GENERATED_BY;
	}

	public static function generatedSignature():String {
		return GENERATED_SIGNATURE;
	}

	public static function manifestFilename():String {
		return MANIFEST_FILENAME;
	}

	public static function liveReactRepository():String {
		return LIVE_REACT_REPOSITORY;
	}

	public static function liveReactRevision():String {
		return LIVE_REACT_REVISION;
	}

	public static function compatibility():Compatibility {
		return {
			repository: LIVE_REACT_REPOSITORY,
			revision: LIVE_REACT_REVISION,
			react: "19.1.0",
			react_dom: "19.1.0",
			vite: "7.2.7"
		};
	}

	public static function confirmationPrompt(mode:Atom, count:Int):String {
		var action = mode == APPLY ? "Apply" : "Remove";
		return action + " " + Kernel.toString(count) + " owned PhoenixHx LiveReact project change(s)?";
	}

	public static function clientModeLabel(mode:Atom):String {
		return mode == GENES ? "genes" : "plain-js";
	}

	public static function runtimePolicy():Map<String, Bool> {
		return [
			"trustedFirstPartyOnly" => true,
			"ssr" => false,
			"slots" => false,
			"uploads" => false,
			"streams" => false,
			"rawBridgeDefault" => false
		];
	}

	public static function renderViteConfig(packageRootRelative:String):String {
		var projectRootExpression = packageRootRelative == "." ? "packageRoot" : "path.dirname(packageRoot)";

		return joinLines([
			'// $GENERATED_SIGNATURE',
			'import path from "node:path"',
			'import {fileURLToPath} from "node:url"',
			'import react from "@vitejs/plugin-react"',
			'import {defineConfig} from "vite"',
			'import liveReactPlugin from "live_react/vite-plugin"',
			'',
			'const packageRoot = path.dirname(fileURLToPath(import.meta.url))',
			'const projectRoot = $projectRootExpression',
			'const assetRoot = path.join(projectRoot, "assets")',
			'',
			'export default defineConfig(({command}) => ({',
			'  root: assetRoot,',
			'  base: command === "build" ? "/assets/" : undefined,',
			'  publicDir: false,',
			'  plugins: [react(), liveReactPlugin()],',
			'  server: {',
			'    host: "127.0.0.1",',
			'    port: 5173,',
			'    strictPort: true,',
			'  },',
			'  resolve: {',
			'    dedupe: ["react", "react-dom"],',
			'  },',
			'  optimizeDeps: {',
			'    include: ["live_react", "phoenix", "phoenix_html", "phoenix_live_view"],',
			'  },',
			'  build: {',
			'    commonjsOptions: {transformMixedEsModules: true},',
			'    target: "es2020",',
			'    outDir: path.join(projectRoot, "priv/static/assets"),',
			'    emptyOutDir: false,',
			'    sourcemap: true,',
			'    manifest: false,',
			'    rollupOptions: {',
			'      input: {',
			'        app: path.join(assetRoot, "js/app.js"),',
			'      },',
			'      output: {',
			'        entryFileNames: "[name].js",',
			'        chunkFileNames: "[name]-[hash].js",',
			'        assetFileNames: "[name][extname]",',
			'      },',
			'    },',
			'  },',
			'}))'
		]);
	}

	public static function renderHooksFile():String {
		return joinLines([
			'// $GENERATED_SIGNATURE',
			'import {getHooks} from "live_react"',
			'import componentRegistry from "../react-components/registry.generated.js"',
			'',
			'export const reactHooks = getHooks(componentRegistry)'
		]);
	}

	public static function renderRegistryFile():String {
		return joinLines([
			'// $GENERATED_SIGNATURE',
			'export const componentRegistry = {}',
			'',
			'export default componentRegistry'
		]);
	}

	public static function liveReactDependencyLines():Array<String> {
		return [
			"{:live_react,",
			' git: "$LIVE_REACT_REPOSITORY",',
			' ref: "$LIVE_REACT_REVISION"},'
		];
	}

	public static function packageCommand(packageRootRelative:String, command:String):String {
		return packageRootRelative == "." ? '"cmd $command",' : '"cmd --cd $packageRootRelative $command",';
	}

	public static function liveReactConfigLines():Array<String> {
		return [
			"# Stock LiveReact remains client-only in the initial PhoenixHx integration.",
			"config :live_react, ssr: false"
		];
	}

	public static function liveReactDevConfigLines():Array<String> {
		return [
			"config :live_react,",
			"  vite_host:",
			'    if(System.get_env("DISABLE_WATCHERS") == "1", do: nil, else: "http://127.0.0.1:5173"),',
			"  ssr: false",
			""
		];
	}

	public static function liveReactImportLines():Array<String> {
		return ['import {reactHooks} from "./live-react-hooks.js"'];
	}

	public static function declaredHooksLines():Array<String> {
		return ["Object.assign(Hooks, reactHooks);"];
	}

	public static function windowHooksLines():Array<String> {
		return ["window.Hooks = {...(window.Hooks || {}), ...reactHooks}"];
	}

	public static function viteWatcherLine(packageRootRelative:String):String {
		return
			packageRootRelative == "." ? 'vite: ["npm", "run", "assets:dev", cd: Path.expand("../", __DIR__)],' : 'vite: ["npm", "run", "assets:dev", cd: Path.expand("../$packageRootRelative", __DIR__)],';
	}

	static function joinLines(lines:Array<String>):String {
		var terminatedLines = Enum.concatTwo(lines, [""]);
		return Enum.join(terminatedLines, "\n");
	}
}
