package;

import reflaxe.elixir.macros.HttpMethod;

/**
 * Valid controller class for testing RouterBuildMacro validation
 */
class ExistingController {
    public static function index(): String {
        return "Existing controller index";
    }
}

/**
 * Router test with INVALID controller reference
 * This should produce a warning about missing controller
 */
@:router
@:build(reflaxe.elixir.macros.RouterBuildMacro.generateRoutes())
@:routes([
    // Valid controller for comparison
    {
        name: "validRoute", 
        method: HttpMethod.GET, 
        path: "/valid", 
        controller: "ExistingController", 
        action: "index"
    },
    
    // Invalid controller reference - should trigger warning
    {
        name: "invalidRoute", 
        method: HttpMethod.GET, 
        path: "/invalid", 
        controller: "NonExistentController", 
        action: "someAction"
    }
])
class InvalidControllerRouterTest {
    // Routes auto-generated by RouterBuildMacro
}

/**
 * Main entry point for test
 */
class Main {
    public static function main() {
        trace("RouterBuildMacro validation test with invalid controller reference");
    }
}