package;

import reflaxe.elixir.macros.HttpMethod;

/**
 * Valid controller class for comparison
 */
class ValidController {
    public static function index(): String {
        return "Valid controller index";
    }
}

/**
 * Another valid controller with limited methods
 */
class PartialController {
    public static function show(): String {
        return "Partial controller show";
    }
    // Missing "create" method
}

/**
 * Router test with MULTIPLE invalid references
 * This should produce multiple warnings for different validation failures
 */
@:router
@:build(reflaxe.elixir.macros.RouterBuildMacro.generateRoutes())
@:routes([
    // Valid route for comparison
    {
        name: "validRoute", 
        method: HttpMethod.GET, 
        path: "/valid", 
        controller: "ValidController", 
        action: "index"
    },
    
    // Invalid controller - should trigger controller warning
    {
        name: "invalidControllerRoute", 
        method: HttpMethod.GET, 
        path: "/invalid-controller", 
        controller: "NonExistentController", 
        action: "someAction"
    },
    
    // Valid controller but invalid action - should trigger action warning
    {
        name: "invalidActionRoute", 
        method: HttpMethod.POST, 
        path: "/invalid-action", 
        controller: "PartialController", 
        action: "create"
    },
    
    // Another invalid controller with different name
    {
        name: "anotherInvalidRoute", 
        method: HttpMethod.DELETE, 
        path: "/another-invalid", 
        controller: "AnotherMissingController", 
        action: "destroy"
    }
])
class MultipleInvalidRouterTest {
    // Routes auto-generated by RouterBuildMacro
}

/**
 * Main entry point for test
 */
class Main {
    public static function main() {
        trace("RouterBuildMacro validation test with multiple invalid references");
    }
}