defmodule HaxePhoenixLiveReact.Core do
  def schema() do
    "phoenixhx.live-react@1"
  end

  def generated_by() do
    "mix haxe.phoenix.live_react"
  end

  def generated_signature() do
    "@generated by mix haxe.phoenix.live_react; do not edit"
  end

  def manifest_filename() do
    "phoenixhx-live-react.json"
  end

  def live_react_repository() do
    "https://github.com/mrdotb/live_react.git"
  end

  def live_react_revision() do
    "055e80e6a4e6d009df5e229eb39e7f85f03fea22"
  end

  def compatibility() do
    %{
      repository: "https://github.com/mrdotb/live_react.git",
      revision: "055e80e6a4e6d009df5e229eb39e7f85f03fea22",
      react: "19.1.0",
      react_dom: "19.1.0",
      vite: "7.2.7"
    }
  end

  def confirmation_prompt(mode, count) do
    action = if mode == :apply, do: "Apply", else: "Remove"
    "#{action} #{Kernel.to_string(count)} owned PhoenixHx LiveReact project change(s)?"
  end

  def client_mode_label(mode) do
    if mode == :genes, do: "genes", else: "plain-js"
  end

  def runtime_policy() do
    %{
      "trustedFirstPartyOnly" => true,
      "ssr" => false,
      "slots" => false,
      "uploads" => false,
      "streams" => false,
      "rawBridgeDefault" => false
    }
  end

  def render_vite_config(package_root_relative) do
    project_root_expression =
      if package_root_relative == ".", do: "packageRoot", else: "path.dirname(packageRoot)"

    join_lines([
      "// @generated by mix haxe.phoenix.live_react; do not edit",
      "import path from \"node:path\"",
      "import {fileURLToPath} from \"node:url\"",
      "import react from \"@vitejs/plugin-react\"",
      "import {defineConfig} from \"vite\"",
      "import liveReactPlugin from \"live_react/vite-plugin\"",
      "",
      "const packageRoot = path.dirname(fileURLToPath(import.meta.url))",
      "const projectRoot = #{project_root_expression}",
      "const assetRoot = path.join(projectRoot, \"assets\")",
      "",
      "export default defineConfig(({command}) => ({",
      "  root: assetRoot,",
      "  base: command === \"build\" ? \"/assets/\" : undefined,",
      "  publicDir: false,",
      "  plugins: [react(), liveReactPlugin()],",
      "  server: {",
      "    host: \"127.0.0.1\",",
      "    port: 5173,",
      "    strictPort: true,",
      "  },",
      "  resolve: {",
      "    dedupe: [\"react\", \"react-dom\"],",
      "  },",
      "  optimizeDeps: {",
      "    include: [\"live_react\", \"phoenix\", \"phoenix_html\", \"phoenix_live_view\"],",
      "  },",
      "  build: {",
      "    commonjsOptions: {transformMixedEsModules: true},",
      "    target: \"es2020\",",
      "    outDir: path.join(projectRoot, \"priv/static/assets\"),",
      "    emptyOutDir: false,",
      "    sourcemap: true,",
      "    manifest: false,",
      "    rollupOptions: {",
      "      input: {",
      "        app: path.join(assetRoot, \"js/app.js\"),",
      "      },",
      "      output: {",
      "        entryFileNames: \"[name].js\",",
      "        chunkFileNames: \"[name]-[hash].js\",",
      "        assetFileNames: \"[name][extname]\",",
      "      },",
      "    },",
      "  },",
      "}))"
    ])
  end

  def render_hooks_file() do
    join_lines([
      "// @generated by mix haxe.phoenix.live_react; do not edit",
      "import {getHooks} from \"live_react\"",
      "import componentRegistry from \"../react-components/registry.generated.js\"",
      "",
      "export const reactHooks = getHooks(componentRegistry)"
    ])
  end

  def render_registry_file() do
    join_lines([
      "// @generated by mix haxe.phoenix.live_react; do not edit",
      "export const componentRegistry = {}",
      "",
      "export default componentRegistry"
    ])
  end

  def live_react_dependency_lines() do
    [
      "{:live_react,",
      " git: \"https://github.com/mrdotb/live_react.git\",",
      " ref: \"055e80e6a4e6d009df5e229eb39e7f85f03fea22\"},"
    ]
  end

  def package_command(package_root_relative, command) do
    if package_root_relative == "." do
      "\"cmd #{command}\","
    else
      "\"cmd --cd #{package_root_relative} #{command}\","
    end
  end

  def live_react_config_lines() do
    [
      "# Stock LiveReact remains client-only in the initial PhoenixHx integration.",
      "config :live_react, ssr: false"
    ]
  end

  def live_react_dev_config_lines() do
    [
      "config :live_react,",
      "  vite_host:",
      "    if(System.get_env(\"DISABLE_WATCHERS\") == \"1\", do: nil, else: \"http://127.0.0.1:5173\"),",
      "  ssr: false",
      ""
    ]
  end

  def live_react_import_lines() do
    ["import {reactHooks} from \"./live-react-hooks.js\""]
  end

  def declared_hooks_lines() do
    ["Object.assign(Hooks, reactHooks);"]
  end

  def window_hooks_lines() do
    ["window.Hooks = {...(window.Hooks || {}), ...reactHooks}"]
  end

  def vite_watcher_line(package_root_relative) do
    if package_root_relative == "." do
      "vite: [\"npm\", \"run\", \"assets:dev\", cd: Path.expand(\"../\", __DIR__)],"
    else
      "vite: [\"npm\", \"run\", \"assets:dev\", cd: Path.expand(\"../#{package_root_relative}\", __DIR__)],"
    end
  end

  defp join_lines(lines) do
    terminated_lines = Enum.concat(lines, [""])
    Enum.join(terminated_lines, "\n")
  end
end
