defmodule HaxePhoenixLiveReact.Registry do
  def component(name, module_path \\ nil, export_name \\ nil) do
    normalized = %{
      name: name,
      module_path:
        if(Kernel.is_nil(module_path), do: default_module_path(name), else: module_path),
      export_name: if(Kernel.is_nil(export_name), do: name <> "Boundary", else: export_name)
    }

    validate_component(normalized)
    normalized
  end

  def components_from_manifest(value) do
    if not Kernel.is_list(value) do
      Kernel.raise("LiveReact manifest components must be a JSON array. No writes occurred.")
    end

    entries = value

    components =
      Enum.map(entries, fn entry ->
        if not Kernel.is_map(entry) do
          Kernel.raise(
            "each LiveReact component entry must be a JSON object. No writes occurred."
          )
        end

        keys = Map.keys(entry)

        if Enum.sort(keys) != ["export", "module", "name"] do
          Kernel.raise(
            "each LiveReact component entry must contain exactly name, module, and export. No writes occurred."
          )
        end

        name = Map.get(entry, "name")
        module_path = Map.get(entry, "module")
        export_name = Map.get(entry, "export")

        if not Kernel.is_binary(name) or not Kernel.is_binary(module_path) or
             not Kernel.is_binary(export_name) do
          Kernel.raise(
            "LiveReact component name, module, and export must be strings. No writes occurred."
          )
        end

        component(
          Kernel.to_string(name),
          Kernel.to_string(module_path),
          Kernel.to_string(export_name)
        )
      end)

    normalized = normalize_components(components)

    if component_names(components) != component_names(normalized) do
      Kernel.raise("LiveReact manifest components must be sorted by name. No writes occurred.")
    end

    normalized
  end

  def normalize_components(components) do
    Enum.each(components, &validate_component/1)
    sorted = Enum.sort_by(components, fn value -> value.name end)

    Enum.reduce(sorted, nil, fn value, previous ->
      if previous == value.name do
        Kernel.raise(
          "duplicate LiveReact component name " <>
            value.name <> ". No writes occurred. Component names are static registry identities."
        )
      end

      value.name
    end)

    sorted
  end

  def to_manifest_terms(components) do
    Enum.map(normalize_components(components), fn value ->
      entry = Map.new()
      entry = entry |> Map.put("name", value.name) |> Map.put("module", value.module_path)
      Map.put(entry, "export", value.export_name)
    end)
  end

  def render_registry_file(components) do
    normalized = normalize_components(components)

    imports =
      Enum.map(normalized, fn value ->
        "import {" <>
          value.export_name <>
          " as " <> value.name <> "Component} from \"" <> value.module_path <> "\""
      end)

    entries =
      Enum.map(normalized, fn value ->
        "  " <> value.name <> ": " <> value.name <> "Component,"
      end)

    join_sections([
      ["/* @generated by mix haxe.phoenix.live_react; do not edit */"],
      imports,
      ["export const componentRegistry = {"],
      entries,
      [
        "} as const",
        "",
        "export type ComponentName = keyof typeof componentRegistry",
        "",
        "export default componentRegistry"
      ]
    ])
  end

  def render_haxe_wrapper(app_name, value) do
    validate_app_name(app_name)
    validate_component(value)
    package_name = "#{app_name}_hx.components.live_react"
    native_module = "#{Macro.camelize(app_name)}Web.ReactIslands.#{value.name}"

    join_lines([
      "package #{package_name};",
      "",
      "import phoenix.live_react.LiveReact;",
      "import phoenix.types.Assigns;",
      "",
      "private typedef #{value.name}Assigns = {",
      "\tvar id:String;",
      "\tvar title:String;",
      "}",
      "",
      "/**",
      " * Hand-owned typed Phoenix boundary for the fixed #{value.name} React island.",
      " *",
      " * Keep the component name and SSR posture static. Extend this closed assigns",
      " * type alongside the trusted TypeScript boundary when adding public props.",
      " */",
      "@:native(\"#{native_module}\")",
      "@:component",
      "class #{value.name}Island {",
      "\t@:component",
      "\tpublic static function render(assigns:Assigns<#{value.name}Assigns>):String {",
      "\t\treturn <div class=\"react-island-host\">",
      "\t\t\t<LiveReact.react",
      "\t\t\t\tid=${assigns.id}",
      "\t\t\t\tname=\"#{value.name}\"",
      "\t\t\t\ttitle=${assigns.title}",
      "\t\t\t\tssr=${false}",
      "\t\t\t/>",
      "\t\t</div>;",
      "\t}",
      "}"
    ])
  end

  def render_boundary(value) do
    validate_component(value)
    slug = component_slug(value.name)

    join_lines([
      "import {#{value.name}} from \"./#{slug}\"",
      "",
      "export type #{value.name}RawProps = Record<string, unknown>",
      "",
      "interface #{value.name}Input {",
      "  readonly title: string",
      "}",
      "",
      "const publicInputKeys = new Set([\"title\"])",
      "const nativeBridgeKeys = new Set([",
      "  \"pushEvent\",",
      "  \"pushEventTo\",",
      "  \"handleEvent\",",
      "  \"removeHandleEvent\",",
      "  \"upload\",",
      "  \"uploadTo\",",
      "])",
      "",
      "function decode#{value.name}Input(value: Record<string, unknown>): #{value.name}Input {",
      "  if (Object.keys(value).length !== 1 || typeof value.title !== \"string\" || value.title.trim() === \"\") {",
      "    throw new Error(\"#{value.name} expects exactly one non-empty string prop: title\")",
      "  }",
      "  return {title: value.title}",
      "}",
      "",
      "/**",
      " * Trusted stock LiveReact adapter. It narrows capabilities for a first-party",
      " * component; it is not a sandbox for untrusted React code.",
      " */",
      "export function #{value.export_name}(raw: #{value.name}RawProps) {",
      "  try {",
      "    const publicInput: Record<string, unknown> = {}",
      "    for (const [key, candidate] of Object.entries(raw)) {",
      "      if (nativeBridgeKeys.has(key)) continue",
      "      if (!publicInputKeys.has(key)) throw new Error(\"Unexpected #{value.name} input: \" + key)",
      "      publicInput[key] = candidate",
      "    }",
      "",
      "    const input = decode#{value.name}Input(publicInput)",
      "    return <#{value.name} {...input} />",
      "  } catch (error) {",
      "    const message = error instanceof Error ? error.message : \"Unknown React boundary error\"",
      "    return (",
      "      <section role=\"alert\" data-live-react-boundary=\"error\">",
      "        <strong>#{value.name} is unavailable.</strong>",
      "        <span>{message}</span>",
      "      </section>",
      "    )",
      "  }",
      "}"
    ])
  end

  def render_inner_component(value) do
    validate_component(value)
    slug = component_slug(value.name)

    join_lines([
      "export interface #{value.name}Props {",
      "  readonly title: string",
      "}",
      "",
      "/** Hand-owned, unstyled starter. Apply the host application's visual system here. */",
      "export function #{value.name}({title}: #{value.name}Props) {",
      "  return (",
      "    <section data-react-island=\"#{slug}\">",
      "      <p aria-hidden=\"true\">React island</p>",
      "      <h2>{title}</h2>",
      "    </section>",
      "  )",
      "}"
    ])
  end

  def default_module_path(name) do
    validate_name(name)
    "./#{component_slug(name)}-boundary"
  end

  def component_slug(name) do
    validate_name(name)
    String.replace(Macro.underscore(name), "_", "-")
  end

  def wrapper_relative_path(app_name, value) do
    validate_app_name(app_name)

    Path.join([
      "src_haxe",
      "#{app_name}_hx",
      "components",
      "live_react",
      "#{value.name}Island.hx"
    ])
  end

  def boundary_relative_path(value) do
    Path.join(["assets", "react-components", "#{component_slug(value.name)}-boundary.tsx"])
  end

  def inner_relative_path(value) do
    Path.join(["assets", "react-components", "#{component_slug(value.name)}.tsx"])
  end

  def boundary_candidates(value) do
    validate_component(value)
    relative = String.replace_prefix(value.module_path, "./", "")
    extension = Path.extname(relative)

    if extension == "" do
      Enum.map([".tsx", ".ts", ".jsx", ".js"], fn suffix -> relative <> suffix end)
    else
      [relative]
    end
  end

  defp validate_component(value) do
    validate_name(value.name)

    if not Regex.match?(Regex.compile!("^\\./[A-Za-z0-9][A-Za-z0-9_./-]*$"), value.module_path) or
         String.contains?(value.module_path, "//") or
         Enum.member?(Path.split(value.module_path), "..") do
      Kernel.raise(
        "invalid LiveReact component module #{Kernel.inspect(value.module_path)}. Expected a closed project-relative import such as ./preference-studio-boundary. No writes occurred."
      )
    end

    if not Regex.match?(Regex.compile!("^[A-Za-z_$][A-Za-z0-9_$]*$"), value.export_name) do
      Kernel.raise(
        "invalid LiveReact component export #{Kernel.inspect(value.export_name)}. Expected a JavaScript identifier. No writes occurred."
      )
    end
  end

  defp validate_name(name) do
    if not Regex.match?(Regex.compile!("^[A-Z][A-Za-z0-9]*$"), name) do
      Kernel.raise(
        "invalid LiveReact component name #{Kernel.inspect(name)}. Expected a static PascalCase identifier such as PreferenceStudio. No writes occurred."
      )
    end
  end

  defp validate_app_name(app_name) do
    if not Regex.match?(Regex.compile!("^[a-z][a-z0-9_]*$"), app_name) do
      Kernel.raise(
        "invalid Mix application name #{Kernel.inspect(app_name)}. Expected a lowercase underscore identifier. No writes occurred."
      )
    end
  end

  defp component_names(components) do
    Enum.map(components, fn value -> value.name end)
  end

  defp join_sections(sections) do
    non_empty = Enum.filter(sections, fn section -> length(section) != 0 end)

    lines =
      Enum.reduce(non_empty, [], fn section, current ->
        if length(current) == 0 do
          section
        else
          Enum.concat(Enum.concat(current, [""]), section)
        end
      end)

    join_lines(lines)
  end

  defp join_lines(lines) do
    Enum.join(Enum.concat(lines, [""]), "\n")
  end
end
