import Config

disable_watchers = System.get_env("DISABLE_WATCHERS") == "1"

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :phoenixhx_live_react, PhoenixhxLiveReactWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "lq6PyChaLkCu4KXIut/vjn7zntlYzziZr8/onjlpy4APaGuwLg7ixmZ5bC739P8S",
  watchers:
    if(disable_watchers,
      do: [],
      else: [
        # BEGIN reflaxe_elixir haxe_client
        # Haxe client JS build:
        # - Compiles to assets/js/_hx_app_tmp.js (temp output Haxe may delete during rebuilds).
        # - Promotes to assets/js/hx_app.js (stable import path for Vite).
        haxe_client: [
          "mix",
          "haxe.watch",
          "--hxml",
          "build-client.hxml",
          "--dirs",
          "src_haxe",
          "--debounce",
          "150",
          "--promote",
          "assets/js/_hx_app_tmp.js:assets/js/hx_app.js,assets/js/_hx_app_tmp.js.map:assets/js/hx_app.js.map",
          cd: Path.expand("../", __DIR__)
        ],
        # END reflaxe_elixir haxe_client

        # BEGIN reflaxe_elixir live_react_vite_watcher
        npm: ["run", "assets:dev", cd: Path.expand("../", __DIR__)],
        # END reflaxe_elixir live_react_vite_watcher
        tailwind: {Tailwind, :install_and_run, [:phoenixhx_live_react, ~w(--watch)]}
      ]
    )

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :phoenixhx_live_react, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false

# BEGIN reflaxe_elixir live_react_vite_host
config :live_react,
  vite_host:
    if(System.get_env("DISABLE_WATCHERS") == "1", do: nil, else: "http://127.0.0.1:5173"),
  ssr: false

# END reflaxe_elixir live_react_vite_host
