Code.require_file("std.ex", __DIR__)
Code.require_file("haxe/log.ex", __DIR__)
Code.require_file("haxe/io/bytes.ex", __DIR__)
Code.require_file("enhanced_pattern_matching_test.ex", __DIR__)
EnhancedPatternMatchingTest.main()