// Generated by Haxe 4.3.7
(function ($global) { "use strict";
var $estr = function() { return js_Boot.__string_rec(this,''); },$hxEnums = $hxEnums || {},$_;
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var ResourceHookEvent = $hxEnums["ResourceHookEvent"] = { __ename__:true,__constructs__:null
	,ResourceSelected: ($_=function(payload) { return {_hx_index:0,payload:payload,__enum__:"ResourceHookEvent",toString:$estr}; },$_._hx_name="ResourceSelected",$_.__params__ = ["payload"],$_)
	,Ping: {_hx_name:"Ping",_hx_index:1,__enum__:"ResourceHookEvent",toString:$estr}
};
ResourceHookEvent.__constructs__ = [ResourceHookEvent.ResourceSelected,ResourceHookEvent.Ping];
var Main = function() { };
Main.__name__ = true;
Main.main = function() {
	var pushed = [];
	var hook = { el : null, pushEvent : function(event,payload) {
		var nested = payload == null ? null : ((p,k)=>{var v=p[k]; if(v!=null && typeof v==='object' && !Array.isArray(v)) return v; return null;})(payload,"resource_id");
		var id = nested == null ? null : nested == null ? null : ((p,k)=>{var v=p[k]; if(v==null) return null; if(typeof v==='number') return (v|0); if(typeof v==='string'){var n=parseInt(v,10); return Number.isFinite(n)?(n|0):null;} return null;})(nested,"value");
		pushed.push(event + ":" + id + ":" + (payload == null ? null : ((p,k)=>{var v=p[k]; return (typeof v==='string') ? v : null;})(payload,"source")));
	}};
	ResourceHookEvents.pushResourceSelected(hook,{ resourceId : 42, source : "row"});
	ResourceHookEvents.push(hook,ResourceHookEvent.ResourceSelected({ resourceId : 43, source : "keyboard"}));
	ResourceHookEvents.pushPing(hook);
	if(pushed.length != 3) {
		throw haxe_Exception.thrown("expected three pushed events");
	}
};
Math.__name__ = true;
var ResourceId = {};
ResourceId._new = function(value) {
	return value;
};
var ResourceIdCodec = function() { };
ResourceIdCodec.__name__ = true;
ResourceIdCodec.codec = function() {
	return { encode : function(value) {
		var payload = { };
		if(payload == null) {
			return payload;
		} else {
			payload["value"] = value;
			return payload;
		}
	}, decode : function(payload) {
		var value = payload == null ? null : ((p,k)=>{var v=p[k]; if(v==null) return null; if(typeof v==='number') return (v|0); if(typeof v==='string'){var n=parseInt(v,10); return Number.isFinite(n)?(n|0):null;} return null;})(payload,"value");
		if(value == null) {
			return null;
		} else {
			return value;
		}
	}};
};
var ResourceHookEvents = function() { };
ResourceHookEvents.__name__ = true;
ResourceHookEvents.encode = function(event) {
	switch(event._hx_index) {
	case 0:
		var payload = event.payload;
		return { event : "resource_selected", payload : { resource_id : ResourceIdCodec.codec().encode(payload.resourceId), source : payload.source}};
	case 1:
		return { event : "ping", payload : { }};
	}
};
ResourceHookEvents.decode = function(eventName,payload) {
	if(eventName == "ping") {
		return ResourceHookEvent.Ping;
	} else if(eventName == "resource_selected") {
		var resourceIdRaw = (payload == null ? null : payload["resource_id"]);
		var resourceId = resourceIdRaw != null ? ResourceIdCodec.codec().decode(resourceIdRaw) : null;
		var sourceRaw = (payload == null ? null : payload["source"]);
		var source = (typeof sourceRaw === 'string' ? sourceRaw : null);
		if(resourceId != null && source != null) {
			return ResourceHookEvent.ResourceSelected({ resourceId : resourceId, source : source});
		} else {
			return null;
		}
	} else {
		return null;
	}
};
ResourceHookEvents.push = function(hook,event) {
	var encoded = ResourceHookEvents.encode(event);
	if(hook.pushEvent != null) {
		hook.pushEvent(encoded.event,encoded.payload);
	}
};
ResourceHookEvents.pushPing = function(hook) {
	if(hook.pushEvent != null) {
		hook.pushEvent("ping",{ });
	}
};
ResourceHookEvents.pushResourceSelected = function(hook,payload) {
	if(hook.pushEvent != null) {
		var tmp = ResourceIdCodec.codec().encode(payload.resourceId);
		hook.pushEvent("resource_selected",{ resource_id : tmp, source : payload.source});
	}
};
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.__name__ = true;
haxe_Exception.thrown = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value.get_native();
	} else if(((value) instanceof Error)) {
		return value;
	} else {
		var e = new haxe_ValueException(value);
		return e;
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	get_native: function() {
		return this.__nativeException;
	}
});
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__name__ = true;
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
});
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.__name__ = true;
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var js_Boot = function() { };
js_Boot.__name__ = true;
js_Boot.__string_rec = function(o,s) {
	if(o == null) {
		return "null";
	}
	if(s.length >= 5) {
		return "<...>";
	}
	var t = typeof(o);
	if(t == "function" && (o.__name__ || o.__ename__)) {
		t = "object";
	}
	switch(t) {
	case "function":
		return "<function>";
	case "object":
		if(o.__enum__) {
			var e = $hxEnums[o.__enum__];
			var con = e.__constructs__[o._hx_index];
			var n = con._hx_name;
			if(con.__params__) {
				s = s + "\t";
				return n + "(" + ((function($this) {
					var $r;
					var _g = [];
					{
						var _g1 = 0;
						var _g2 = con.__params__;
						while(true) {
							if(!(_g1 < _g2.length)) {
								break;
							}
							var p = _g2[_g1];
							_g1 = _g1 + 1;
							_g.push(js_Boot.__string_rec(o[p],s));
						}
					}
					$r = _g;
					return $r;
				}(this))).join(",") + ")";
			} else {
				return n;
			}
		}
		if(((o) instanceof Array)) {
			var str = "[";
			s += "\t";
			var _g = 0;
			var _g1 = o.length;
			while(_g < _g1) {
				var i = _g++;
				str += (i > 0 ? "," : "") + js_Boot.__string_rec(o[i],s);
			}
			str += "]";
			return str;
		}
		var tostr;
		try {
			tostr = o.toString;
		} catch( _g ) {
			return "???";
		}
		if(tostr != null && tostr != Object.toString && typeof(tostr) == "function") {
			var s2 = o.toString();
			if(s2 != "[object Object]") {
				return s2;
			}
		}
		var str = "{\n";
		s += "\t";
		var hasp = o.hasOwnProperty != null;
		var k = null;
		for( k in o ) {
		if(hasp && !o.hasOwnProperty(k)) {
			continue;
		}
		if(k == "prototype" || k == "__class__" || k == "__super__" || k == "__interfaces__" || k == "__properties__") {
			continue;
		}
		if(str.length != 2) {
			str += ", \n";
		}
		str += s + k + " : " + js_Boot.__string_rec(o[k],s);
		}
		s = s.substring(1);
		str += "\n" + s + "}";
		return str;
	case "string":
		return o;
	default:
		return String(o);
	}
};
var phoenix_channels_WirePayload = function() { };
phoenix_channels_WirePayload.__name__ = true;
phoenix_channels_WirePayload.empty = function() {
	return { };
};
phoenix_channels_WirePayload.putPayload = function(payload,key,value) {
	if(payload == null || key == null) {
		return payload;
	}
	payload[key] = value;
	return payload;
};
phoenix_channels_WirePayload.putString = function(payload,key,value) {
	if(payload == null || key == null) {
		return payload;
	}
	payload[key] = value;
	return payload;
};
phoenix_channels_WirePayload.putInt = function(payload,key,value) {
	if(payload == null || key == null) {
		return payload;
	}
	payload[key] = value;
	return payload;
};
phoenix_channels_WirePayload.putBool = function(payload,key,value) {
	if(payload == null || key == null) {
		return payload;
	}
	payload[key] = value;
	return payload;
};
phoenix_channels_WirePayload.putFloat = function(payload,key,value) {
	if(payload == null || key == null) {
		return payload;
	}
	payload[key] = value;
	return payload;
};
phoenix_channels_WirePayload.putStringArray = function(payload,key,value) {
	if(payload == null || key == null) {
		return payload;
	}
	payload[key] = value;
	return payload;
};
phoenix_channels_WirePayload.putIntArray = function(payload,key,value) {
	if(payload == null || key == null) {
		return payload;
	}
	payload[key] = value;
	return payload;
};
phoenix_channels_WirePayload.getPayload = function(payload,key) {
	if(payload == null || key == null) {
		return null;
	}
	return ((p,k)=>{var v=p[k]; if(v!=null && typeof v==='object' && !Array.isArray(v)) return v; return null;})(payload,key);
};
phoenix_channels_WirePayload.getString = function(payload,key) {
	if(payload == null || key == null) {
		return null;
	}
	return ((p,k)=>{var v=p[k]; return (typeof v==='string') ? v : null;})(payload,key);
};
phoenix_channels_WirePayload.getInt = function(payload,key) {
	if(payload == null || key == null) {
		return null;
	}
	return ((p,k)=>{var v=p[k]; if(v==null) return null; if(typeof v==='number') return (v|0); if(typeof v==='string'){var n=parseInt(v,10); return Number.isFinite(n)?(n|0):null;} return null;})(payload,key);
};
phoenix_channels_WirePayload.getBool = function(payload,key) {
	if(payload == null || key == null) {
		return null;
	}
	return ((p,k)=>{var v=p[k]; if(typeof v==='boolean') return v; return null;})(payload,key);
};
phoenix_channels_WirePayload.getFloat = function(payload,key) {
	if(payload == null || key == null) {
		return null;
	}
	return ((p,k)=>{var v=p[k]; if(v==null) return null; if(typeof v==='number') return v; if(typeof v==='string'){var n=parseFloat(v); return Number.isFinite(n)?n:null;} return null;})(payload,key);
};
phoenix_channels_WirePayload.getStringArray = function(payload,key) {
	if(payload == null || key == null) {
		return null;
	}
	return ((p,k)=>{var v=p[k]; if(!Array.isArray(v)) return null; for(var i=0;i<v.length;i++){if(typeof v[i] !== 'string') return null;} return v;})(payload,key);
};
phoenix_channels_WirePayload.getIntArray = function(payload,key) {
	if(payload == null || key == null) {
		return null;
	}
	return ((p,k)=>{var v=p[k]; if(!Array.isArray(v)) return null; var out=[]; for(var i=0;i<v.length;i++){var x=v[i]; if(typeof x==='number'){out.push(x|0); continue;} if(typeof x==='string'){var n=parseInt(x,10); if(Number.isFinite(n)){out.push(n|0); continue;} } return null;} return out;})(payload,key);
};
var phoenix_live_$view_LiveEventProtocolCompanion = function() { };
phoenix_live_$view_LiveEventProtocolCompanion.__name__ = true;
String.__name__ = true;
Array.__name__ = true;
js_Boot.__toStr = ({ }).toString;
ResourceHookEvents.PingEvent = "ping";
ResourceHookEvents.ResourceSelectedEvent = "resource_selected";
Main.main();
})({});
