Code.require_file("bitwise_operations.ex", __DIR__)
Code.require_file("haxe/log.ex", __DIR__)
Code.require_file("std.ex", __DIR__)
Code.require_file("test_app_web.test_component.ex", __DIR__)
Code.require_file("main.ex", __DIR__)
Main.main()