package;

import reflaxe.elixir.macros.HttpMethod;

/**
 * Valid controller class with limited methods for testing RouterBuildMacro action validation
 */
class LimitedController {
    public static function index(): String {
        return "Limited controller index";
    }
    
    public static function show(): String {
        return "Limited controller show";
    }
    
    // Note: No "create" or "nonExistentAction" methods
}

/**
 * Router test with INVALID action reference
 * This should produce a warning about missing action method
 */
@:router
@:build(reflaxe.elixir.macros.RouterBuildMacro.generateRoutes())
@:routes([
    // Valid controller and action for comparison
    {
        name: "validRoute", 
        method: HttpMethod.GET, 
        path: "/valid", 
        controller: "LimitedController", 
        action: "index"
    },
    
    // Valid controller but invalid action - should trigger warning
    {
        name: "invalidActionRoute", 
        method: HttpMethod.POST, 
        path: "/invalid-action", 
        controller: "LimitedController", 
        action: "nonExistentAction"
    }
])
class InvalidActionRouterTest {
    // Routes auto-generated by RouterBuildMacro
}

/**
 * Main entry point for test
 */
class Main {
    public static function main() {
        trace("RouterBuildMacro validation test with invalid action reference");
    }
}