Code.require_file("_main/user_id_impl_.ex", __DIR__)
Code.require_file("std.ex", __DIR__)
Code.require_file("_main/money_impl_.ex", __DIR__)
Code.require_file("haxe/log.ex", __DIR__)
Code.require_file("main.ex", __DIR__)
Main.main()