[output] = System.argv()
{:ok, _, []} = Kernel.ParallelCompiler.compile(Path.wildcard(Path.join(output, "**/*.ex")), warnings_as_errors: true)
{:ok, _} = Application.ensure_all_started(:phoenix_pubsub)
{:ok, _} = Supervisor.start_link([{Phoenix.PubSub, name: MyApp.PubSub}, MyAppWeb.ChatPresence, MyAppWeb.SpecialPresence], strategy: :one_for_one)
socket = %Phoenix.Socket{}
^socket = MyAppWeb.NormalModule.track_from_outside(socket, "reader")
%{"reader" => %{metas: [%{status: "outside"}]}} = MyAppWeb.NormalModule.list_from_outside()
^socket = MyAppWeb.NormalModule.update_from_outside(socket, "reader")
%{metas: [%{status: "updated"}]} = MyAppWeb.ChatPresence.get_user_by_key("reader")
nil = MyAppWeb.ChatPresence.get_user_by_key("missing")
^socket = MyAppWeb.SpecialPresence.track_with_string_op(socket, "")
%{"anonymous" => %{metas: [%{status: "special"}]}} = MyAppWeb.SpecialPresence.list("special")
^socket = MyAppWeb.ChatPresence.untrack_user(socket, "reader")
%{} = MyAppWeb.ChatPresence.list_users()
IO.puts("declared Presence targets preserve tracking, update, lookup and removal")
