Code.require_file("haxe/validation/_user_id/user_id_impl_.ex", __DIR__)
Code.require_file("std.ex", __DIR__)
Code.require_file("haxe/functional/result_tools.ex", __DIR__)
Code.require_file("haxe/validation/_positive_int/positive_int_impl_.ex", __DIR__)
Code.require_file("haxe/log.ex", __DIR__)
Code.require_file("haxe/validation/_email/email_impl_.ex", __DIR__)
Code.require_file("string_tools.ex", __DIR__)
Code.require_file("haxe/validation/_non_empty_string/non_empty_string_impl_.ex", __DIR__)
Code.require_file("main.ex", __DIR__)
Main.main()