package live;

import contexts.Analytics;
import contexts.Analytics.Metric;

// Import HXX for template processing
import HXX.*;

/**
 * Phoenix LiveView module for DashboardLive
 * Generated by mix haxe.gen.live
 */
@:liveview
class DashboardLive {
    
    var metrics: Array<Metric> = [];
var selectedMetric: Null<Metric> = null;
var changeset: Dynamic = null;

    var showModal: Bool = false;
    var sortBy: String = "id";
var sortOrder: String = "asc";
var filterText: String = "";
var currentPage: Int = 1;
var perPage: Int = 10;

    
    function mount(params: Dynamic, session: Dynamic, socket: Dynamic): {status: String, socket: Dynamic} {
        metrics = Analytics.list_metrics();
        
        return {
            status: "ok",
            socket: assign_multiple(socket, {
                sortBy: "id",
                    sortOrder: "asc",
                    filterText: "",
                    currentPage: 1,
                    perPage: 10,
                    showModal: false,
                    metrics: metrics,
                    selectedMetric: null,
                    changeset: null
            })
        };
    }
    
    function handle_event(event: String, params: Dynamic, socket: Dynamic): {status: String, socket: Dynamic} {
        return switch(event) {
            case "load_metric": handle_load(params, socket);
                case "new_metric": handle_new(params, socket);
                case "edit_metric": handle_edit(params, socket);
                case "save": handle_save(params, socket);
                case "paginate": handle_paginate(params, socket);
                case "filter": handle_filter(params, socket);
                case "sort": handle_sort(params, socket);
                case "close_modal": handle_close_modal(socket);
            
            default:
                {status: "noreply", socket: socket};
        }
    }
    
    function handle_new(params: Dynamic, socket: Dynamic): {status: String, socket: Dynamic} {
    changeset = Analytics.change_metric(null);
    selectedMetric = null;
    showModal = true;
    
    return {
        status: "noreply",
        socket: assign_multiple(socket, {
            changeset: changeset,
            selectedMetric: null,
                showModal: true
        })
    };
}

    function handle_edit(params: Dynamic, socket: Dynamic): {status: String, socket: Dynamic} {
    var id = params.id;
    selectedMetric = Analytics.get_metric(id);
    changeset = Analytics.change_metric(selectedMetric);
    showModal = true;
    
    return {
        status: "noreply",
        socket: assign_multiple(socket, {
            selectedMetric: selectedMetric,
            changeset: changeset,
                showModal: true
        })
    };
}

    function handle_save(params: Dynamic, socket: Dynamic): {status: String, socket: Dynamic} {
    var metric_params = params.metric;
    var result = selectedMetric == null
        ? Analytics.create_metric(metric_params)
        : Analytics.update_metric(selectedMetric, metric_params);
        
    return switch(result.status) {
        case "ok":
            metrics = Analytics.list_metrics();
            showModal = false;
            
            {
                status: "noreply",
                socket: assign_multiple(socket, {
                    metrics: metrics,
                    selectedMetric: null,
                    changeset: null,
                        showModal: false
                })
            };
            
        case "error":
            {
                status: "noreply",
                socket: assign(socket, "changeset", result.changeset)
            };
            
        default:
            {status: "noreply", socket: socket};
    }
}

    
    
    
    function render(assigns: Dynamic): String {
    return hxx('
    <div class="metric">
        <div class="header">
            <h1>Metric Management</h1>
            <.button phx-click="new_metric" class="btn-primary">
    <.icon name="plus" /> New Metric
</.button>

        </div>
        
        <div class="data-table">
    <div class="table-controls">
        <.form phx-change="filter">
            <.input 
                name="filter"
                value={@filterText}
                placeholder="Filter..."
                type="search"
            />
        </.form>
    </div>
    
    <table class="table">
        <thead>
            <tr>
                <th phx-click="sort" phx-value-field="id">
                    ID {@sortBy == "id" ? (@sortOrder == "asc" ? "↑" : "↓") : ""}
                </th>
                <th phx-click="sort" phx-value-field="name">
                    Name {@sortBy == "name" ? (@sortOrder == "asc" ? "↑" : "↓") : ""}
                </th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <!-- Render table rows here -->
        </tbody>
    </table>
    
    <div class="pagination">
        <.button phx-click="paginate" phx-value-page={@currentPage - 1} disabled={@currentPage == 1}>
            Previous
        </.button>
        <span>Page {@currentPage}</span>
        <.button phx-click="paginate" phx-value-page={@currentPage + 1}>
            Next
        </.button>
    </div>
</div>

        
        ${@showModal ? renderModal(assigns) : ""}

    </div>
    ');
}

    
    
    
    // Helper functions
    static function assign(socket: Dynamic, key: String, value: Dynamic): Dynamic return socket;
    static function assign_multiple(socket: Dynamic, assigns: Dynamic): Dynamic return socket;
    
    
    
    public static function main(): Void {
        trace("DashboardLive LiveView compiled successfully!");
    }
}
