/* @generated by scripts/apply-live-react-binding.mjs; do not edit */
export const LIVE_REACT_SOURCE_REVISION = "055e80e6a4e6d009df5e229eb39e7f85f03fea22" as const
export const PREFERENCE_DENSITIES = ["calm","focused","dense"] as const
export const PREFERENCE_CHANGED_EVENT = "preference_changed" as const
export const MAX_PUBLIC_INPUT_BYTES = 512 as const
export const MAX_EVENT_PAYLOAD_BYTES = 64 as const
