/* @generated by scripts/apply-live-react-binding.mjs; do not edit */
import {PreferenceStudioBoundary} from "./preference-studio-boundary"

export const componentRegistry = {
  PreferenceStudio: PreferenceStudioBoundary,
} as const

export type ComponentName = keyof typeof componentRegistry

export default componentRegistry
