// @generated by mix haxe.phoenix.live_react; do not edit
package todo_app_hx.components.live_react;

import elixir.types.Term;
import phoenix.live_react.LiveReactReload;
import phoenix.types.Assigns;
import phoenix.types.Slot;

private typedef LiveReactViteAssetsAssigns = {
	var assets:Array<String>;
	@:slot var inner_block:Slot<Term>;
}

/**
 * Generated app-local strict-HXX boundary for stock LiveReact development assets.
 * The wrapper forwards the complete assigns/default-slot payload unchanged.
 */
@:native("TodoAppWeb.ReactIslands.LiveReactAssets")
@:component
class LiveReactAssets {
	@:component
	public static function vite_assets(assigns:Assigns<LiveReactViteAssetsAssigns>):Term {
		return LiveReactReload.vite_assets(assigns);
	}
}
