/**
 * Test for infrastructure variable substitution in switch expressions
 * 
 * This test validates that infrastructure variables (like _g, g, g1) 
 * generated by Haxe during switch expression desugaring are properly 
 * substituted with their initialization expressions.
 * 
 * Bug Fixed: Infrastructure variable 'g' appearing in generated Elixir
 * instead of the actual function call (e.g., TodoPubSub.subscribe).
 * 
 * The fix involved adding missing TypedExpr cases to the substituteVariable
 * function: TParenthesis, TMeta, TEnumIndex, and others.
 */

// Mock PubSub for testing
enum PubSubResult<T> {
	Ok(value: T);
	Error(reason: String);
}

class TestPubSub {
	public static function subscribe(topic: String): PubSubResult<String> {
		return Ok("subscribed to " + topic);
	}
}

class Main {
	public static function main() {
		// Test case that reproduces the original bug
		// The switch expression with parentheses would generate 'case (g) do'
		// instead of 'case (TestPubSub.subscribe("notifications")) do'
		var result = switch(TestPubSub.subscribe("notifications")) {
			case Error(reason):
				"Failed: " + reason;
			case Ok(value):
				"Success: " + value;
		}
		trace(result);
	}
}