package server.infrastructure;

/**
 * TodoAppWeb HTTP endpoint
 * Handles incoming HTTP requests and WebSocket connections
 * 
 * This module compiles to TodoAppWeb.Endpoint with proper Phoenix endpoint
 * configuration including plugs, session handling, and LiveView support.
 */
@:native("TodoAppWeb.Endpoint")
@:endpoint
@:appName("TodoApp")
class Endpoint {
    /**
     * Phoenix HTTP endpoint for the TodoApp application
     * 
     * The @:endpoint annotation handles compilation to proper Phoenix.Endpoint module
     * with the following configuration:
     * 
     * - Static file serving from priv/static
     * - LiveView socket configuration at /live
     * - Session cookie configuration with signing
     * - Request parsing (JSON, form data, multipart)
     * - Standard Phoenix plugs (RequestId, Telemetry, etc.)
     * - Router integration with TodoAppWeb.Router
     * 
     * This provides the HTTP layer for:
     * - Serving static assets (CSS, JS, images)
     * - Handling LiveView connections and events
     * - Processing form submissions and API requests
     * - WebSocket communication for real-time features
     */
    
    // The actual Phoenix.Endpoint implementation is generated by the @:endpoint annotation
    // This marker class provides compile-time configuration and type safety
}