package server.infrastructure;

/**
 * TodoApp database repository
 * Provides type-safe database access using Ecto patterns
 * 
 * This module is compiled to TodoApp.Repo with proper Ecto.Repo usage
 * and PostgreSQL adapter configuration for the todo-app application.
 */
@:native("TodoApp.Repo")
@:repo
@:appName("TodoApp")
class Repo {
    /**
     * Repository marker class for Ecto database operations
     * 
     * The @:repo annotation handles compilation to proper Ecto.Repo module
     * with PostgreSQL adapter and application configuration.
     * 
     * This provides type-safe access to all Ecto repository functions:
     * - insert, update, delete operations
     * - get, get_by, all query operations  
     * - transaction and rollback support
     * - migration and schema management
     */
    
    // The actual Ecto.Repo implementation is generated by the @:repo annotation
    // This marker class provides compile-time type safety for database operations
}