Code.require_file("haxe/log.ex", __DIR__)
Code.require_file("std.ex", __DIR__)
Code.require_file("task.ex", __DIR__)
Code.require_file("task.supervisor.ex", __DIR__)
Code.require_file("main.ex", __DIR__)
Main.main()