package live_react_test;

import elixir.Code;
import elixir.ElixirMap;
import elixir.ElixirString;
import elixir.Enum;
import elixir.File;
import elixir.IO;
import elixir.Jason;
import elixir.Kernel;
import elixir.Path;
import elixir.System;
import elixir.ElixirInteger;
import elixir.types.Atom;
import elixir.types.KeywordList;
import elixir.types.Term;
import haxe.test.ExUnit.Callbacks;

typedef OriginalSources = {
	appJs:String,
	configExs:String,
	devExs:String,
	mixExs:String,
	mixLock:String,
	rootLayout:String
}

typedef FileSnapshot = {
	path:String,
	content:String
}

typedef ResolverResult = {
	lock_content:String,
	dependency_path:String
}

enum abstract MixDependencyName(String) to String {
	var JasonLibrary = "jason";
	var ReflaxeElixir = "reflaxe_elixir";
	var LiveReact = "live_react";
}

typedef MixPathDependency = {
	final name:MixDependencyName;
	final path:String;
	final overrideExisting:Bool;
}

/** Deterministic fixture and bounded host helpers shared by the Haxe tests. */
@:native("HaxePhoenixLiveReactTest.Support")
class LiveReactFixture {
	public static inline final REVISION = "055e80e6a4e6d009df5e229eb39e7f85f03fea22";
	public static inline final REPOSITORY = "https://github.com/mrdotb/live_react.git";
	public static inline final MANIFEST = "phoenixhx-live-react.json";
	public static inline final GENERATED_SIGNATURE = "@generated by mix haxe.phoenix.live_react; do not edit";
	public static inline final GENES:Atom = "genes";
	public static inline final PLAIN_JS:Atom = "plain_js";
	static inline final DOLLAR_SIGN = "$";

	static inline final YES:Atom = "yes";
	static inline final MIX_DEPENDENCIES:Atom = "mix_dependencies";
	static inline final GIT_REVISION:Atom = "git_revision";
	static inline final DEPENDENCY_RESOLVER:Atom = "dependency_resolver";
	static inline final LOCK_CONTENT:Atom = "lock_content";
	static inline final DEPENDENCY_PATH:Atom = "dependency_path";
	static inline final PACKAGE_ROOT:Atom = "package_root";
	static inline final APP_NAME:Atom = "app_name";
	static inline final EXISTING:Atom = "existing";
	static inline final MODULE_PATH:Atom = "module_path";
	static inline final EXPORT_NAME:Atom = "export_name";
	static inline final LIVE_REACT:Atom = "live_react";
	static inline final REF:Atom = "ref";
	static inline final GIT:Atom = "git";
	static inline final PATH:Atom = "path";
	static inline final POSITIVE:Atom = "positive";
	static inline final MONOTONIC:Atom = "monotonic";
	static inline final MATCH_DOT:Atom = "match_dot";
	static inline final PRETTY:Atom = "pretty";
	static inline final GLOBAL:Atom = "global";
	static inline final CD:Atom = "cd";
	static inline final ENV:Atom = "env";
	static inline final STDERR_TO_STDOUT:Atom = "stderr_to_stdout";

	public static function fixtureRoot(clientMode:Atom, packageRoot:String):String {
		return fixtureRootWithLayout(clientMode, packageRoot, false);
	}

	public static function fixtureRootWithHaxeLayout(clientMode:Atom, packageRoot:String):String {
		return fixtureRootWithLayout(clientMode, packageRoot, true);
	}

	static function fixtureRootWithLayout(clientMode:Atom, packageRoot:String, haxeLayout:Bool):String {
		var suffix = clientMode == GENES ? "genes" : "plain_js";
		var unique = System.uniqueIntegerWithAtomOptions([POSITIVE, MONOTONIC]);
		var root = Path.joinTwo(System.tmpDirBang(), "reflaxe_live_react_" + suffix + "_" + ElixirInteger.toString(unique));
		Callbacks.onExit(function():Void {
			File.rmRecursiveBang(root);
		});

		write(root, "mix.exs", mixExs());
		write(root, "mix.lock", "%{}\n");
		write(root, "config/config.exs", "import Config\n\nconfig :demo, ecto_repos: []\n");
		write(root, "config/dev.exs", devExs());
		write(root, "assets/js/app.js", appJs(clientMode));
		if (haxeLayout) {
			write(root, "src_haxe/server/layouts/Layouts.hx", haxeRootLayoutSource());
		} else {
			write(root, "lib/demo_web/components/layouts/root.html.heex", rootLayoutSource());
		}
		write(root, Path.joinTwo(packageRoot, "package.json"), "{\"name\":\"demo-assets\"}\n");
		write(root, "deps/live_react/package.json", "{\"name\":\"live_react\",\"version\":\"0.1.0\"}\n");
		write(root, "deps/live_react/mix.exs", liveReactMixExs());

		if (clientMode == GENES) {
			write(root, "build-client.hxml", "-lib genes-ts\n");
			write(root, "src_haxe/client/Boot.hx", "package client; class Boot {}\n");
			write(root, "haxe_libraries/genes-ts.hxml", "# exact test fixture pin\n");
		}
		return root;
	}

	public static function applyOptions(root:String):KeywordList<Term> {
		return resolvedApplyOptions(root, lockContent(true), function(_checkout:String):String return REVISION);
	}

	public static function applyOptionsWithLock(root:String, content:String):KeywordList<Term> {
		return resolvedApplyOptions(root, content, function(_checkout:String):String return REVISION);
	}

	public static function applyOptionsWithRevision(root:String, revisionReader:String->String):KeywordList<Term> {
		return resolvedApplyOptions(root, lockContent(true), revisionReader);
	}

	static function resolvedApplyOptions(root:String, content:String, revisionReader:String->String):KeywordList<Term> {
		var resolver = function(_context:Term):ResolverResult {
			return {
				lock_content: content,
				dependency_path: Path.join([root, "deps", "live_react"])
			};
		};
		return [
			{_0: YES, _1: true},
			{_0: APP_NAME, _1: "demo"},
			{_0: MIX_DEPENDENCIES, _1: []},
			{_0: GIT_REVISION, _1: revisionReader},
			{_0: DEPENDENCY_RESOLVER, _1: resolver}
		];
	}

	public static function rerunOptions():KeywordList<Term> {
		var dependency:Term = {
			_0: LIVE_REACT,
			_1: [{_0: REF, _1: REVISION}, {_0: GIT, _1: REPOSITORY}]
		};
		var revisionReader = function(_checkout:String):String return REVISION;
		return [
			{_0: YES, _1: true},
			{_0: APP_NAME, _1: "demo"},
			{_0: MIX_DEPENDENCIES, _1: [dependency]},
			{_0: GIT_REVISION, _1: revisionReader}
		];
	}

	public static function componentOptions(?existing:Bool = false, ?modulePath:String, ?exportName:String):KeywordList<Term> {
		return [
			{_0: APP_NAME, _1: "demo"},
			{_0: EXISTING, _1: existing},
			{_0: MODULE_PATH, _1: modulePath},
			{_0: EXPORT_NAME, _1: exportName},
			{_0: YES, _1: true}
		];
	}

	public static function pathDependencyOptions(path:String):KeywordList<Term> {
		var dependency:Term = {_0: LIVE_REACT, _1: [{_0: PATH, _1: path}]};
		return [
			{_0: YES, _1: true},
			{_0: APP_NAME, _1: "demo"},
			{_0: MIX_DEPENDENCIES, _1: [dependency]}
		];
	}

	public static function packageRootOptions(root:String, packageRoot:String):KeywordList<Term> {
		return elixir.Keyword.put(applyOptions(root), PACKAGE_ROOT, packageRoot);
	}

	public static function lockContent(includeLiveReact:Bool, ?phoenixVersion:String):String {
		var liveReactLine = '  "live_react": {:git, "$REPOSITORY", "$REVISION", [ref: "$REVISION"]},';
		var phoenixLine = '  "phoenix": {:hex, :phoenix, "$phoenixVersion", "00", [], [], "hexpm", "00"},';
		if (includeLiveReact && phoenixVersion != null)
			return joinLines(["%{", liveReactLine, phoenixLine, "}"]);
		if (includeLiveReact)
			return joinLines(["%{", liveReactLine, "}"]);
		if (phoenixVersion != null)
			return joinLines(["%{", phoenixLine, "}"]);
		return "%{}\n";
	}

	public static function gitLock():Term {
		return {
			_0: GIT,
			_1: REPOSITORY,
			_2: REVISION,
			_3: [{_0: REF, _1: REVISION}]
		};
	}

	public static function readJson(path:String):Term {
		return Jason.decodeStrict(File.readBang(path));
	}

	public static function jsonPath<T>(value:Term, keys:Array<String>):T {
		return cast Enum.reduce(keys, value, function(key:String, current:Term):Term {
			return ElixirMap.fetchBangTerm(current, key);
		});
	}

	public static function encodePretty(value:Term):String {
		return Jason.encodeStrictWithKeywordOptions(value, [{_0: PRETTY, _1: true}]) + "\n";
	}

	public static function originalSources(root:String):OriginalSources {
		return {
			appJs: File.readBang(Path.join([root, "assets", "js", "app.js"])),
			configExs: File.readBang(Path.join([root, "config", "config.exs"])),
			devExs: File.readBang(Path.join([root, "config", "dev.exs"])),
			mixExs: File.readBang(Path.joinTwo(root, "mix.exs")),
			mixLock: File.readBang(Path.joinTwo(root, "mix.lock")),
			rootLayout: File.readBang(rootLayout(root))
		};
	}

	public static function treeSnapshot(root:String):Array<FileSnapshot> {
		var paths = Path.wildcardWithKeywordOptions(Path.joinTwo(root, "**/*"), [{_0: MATCH_DOT, _1: true}]);
		paths = Enum.filter(paths, function(path:String):Bool return File.regular(path));
		paths = Enum.sort(paths);
		return Enum.map(paths, function(path:String):FileSnapshot {
			return {path: Path.relativeTo(path, root), content: File.readBang(path)};
		});
	}

	public static function write(root:String, relative:String, content:String):Void {
		var path = Path.joinTwo(root, relative);
		File.mkdirRecursiveBang(Path.dirname(path));
		File.writeBang(path, content);
	}

	public static function rootLayout(root:String):String {
		var haxeLayout = Path.join([root, "src_haxe", "server", "layouts", "Layouts.hx"]);
		return File.regular(haxeLayout) ? haxeLayout : Path.join([root, "lib", "demo_web", "components", "layouts", "root.html.heex"]);
	}

	public static function replaceOnce(content:String, pattern:String, replacement:String):String {
		return ElixirString.replaceWithKeywordOptions(content, pattern, replacement, [{_0: GLOBAL, _1: false}]);
	}

	public static function copyLiveReactToVendor(root:String):Void {
		File.mkdirRecursiveBang(Path.joinTwo(root, "vendor"));
		File.cpRecursiveBang(Path.join([root, "deps", "live_react"]), Path.join([root, "vendor", "live_react"]));
	}

	public static function pathDependency(name:MixDependencyName, path:String, ?overrideExisting:Bool = false):MixPathDependency {
		return {name: name, path: path, overrideExisting: overrideExisting};
	}

	public static function writeMixProject(root:String, dependencies:Array<MixPathDependency>):Void {
		write(root, "mix.exs", renderMixExs(dependencies));
	}

	public static function formatElixirFile(root:String, relative:String):Void {
		var path = Path.joinTwo(root, relative);
		var formatted = IO.iodataToBinary(Code.formatStringIodataBangOne(File.readBang(path)));
		File.writeBang(path, formatted + "\n");
	}

	public static function runLiveReactTask(root:String, arguments:Array<String>):String {
		return runExternalMix(root, ["haxe.phoenix.live_react"].concat(arguments));
	}

	public static function runExternalMix(root:String, arguments:Array<String>):String {
		var repositoryRoot = File.cwdBang();
		var timeout = Path.join([repositoryRoot, "scripts", "with-timeout.sh"]);
		var options:KeywordList<Term> = [
			{_0: CD, _1: root},
			{_0: ENV, _1: [{_0: "MIX_ENV", _1: "prod"}]},
			{_0: STDERR_TO_STDOUT, _1: true}
		];
		var command = System.cmdWithKeywordOptions(timeout, ["--secs", "60", "--", "mix"].concat(arguments), options);
		if (command._1 != 0)
			return Kernel.raiseValue("LiveReact Mix task failed with status " + ElixirInteger.toString(command._1) + ":\n" + command._0);
		return command._0;
	}

	public static function runNodeSyntaxCheck(root:String, relative:String):Void {
		var repositoryRoot = File.cwdBang();
		var timeout = Path.join([repositoryRoot, "scripts", "with-timeout.sh"]);
		var options:KeywordList<Term> = [{_0: CD, _1: root}, {_0: STDERR_TO_STDOUT, _1: true}];
		var command = System.cmdWithKeywordOptions(timeout, ["--secs", "30", "--", "node", "--check", relative], options);
		if (command._1 != 0)
			Kernel.raiseValue('generated JavaScript syntax check failed for $relative:\n${command._0}');
	}

	/**
	 * Render the external fixture's bootstrap Mix project from typed Haxe data.
	 *
	 * `mix.exs` must declare and fetch `:reflaxe_elixir` before that dependency
	 * can compile any project-owned Haxe, so the file itself cannot be a module
	 * generated by the project being bootstrapped. Keeping target syntax in this
	 * renderer lets tests describe dependencies as `MixPathDependency` values
	 * instead of concatenating Elixir source at each call site.
	 */
	public static function mixExs():String {
		return renderMixExs([]);
	}

	static function renderMixExs(dependencies:Array<MixPathDependency>):String {
		var renderedDependencies = renderMixDependencies(dependencies);

		return joinLines([
			"defmodule Demo.MixProject do",
			"  use Mix.Project",
			"",
			"  def project do",
			"    [app: :demo, version: \"0.1.0\", deps: deps(), aliases: aliases()]",
			"  end",
			"",
			"  def application, do: [extra_applications: [:logger]]",
			"",
			"  defp deps do",
			renderedDependencies,
			"  end",
			"",
			"  defp aliases do",
			"    [",
			"      \"assets.setup\": [\"esbuild.install --if-missing\"],",
			"      \"assets.build\": [\"esbuild demo\"],",
			"      \"assets.deploy\": [\"esbuild demo --minify\", \"phx.digest\"]",
			"    ]",
			"  end",
			"end"
		]);
	}

	static function renderMixDependencies(dependencies:Array<MixPathDependency>):String {
		if (dependencies.length == 0)
			return "    []";

		var entries = Enum.mapJoin(dependencies, ",\n", function(dependency:MixPathDependency):String {
			var overrideOption = dependency.overrideExisting ? ", override: true" : "";
			var dependencyName:String = dependency.name;
			return "      {:" + dependencyName + ", path: " + Jason.encodeStrict(dependency.path) + overrideOption + "}";
		});

		return "    [\n" + entries + "\n    ]";
	}

	public static function devExs():String {
		return joinLines([
			"import Config",
			"",
			"config :demo, DemoWeb.Endpoint,",
			"  http: [ip: {127, 0, 0, 1}, port: 4000],",
			"  watchers: [",
			"    esbuild: {Esbuild, :install_and_run, [:demo, ~w(--sourcemap=inline --watch)]},",
			"    tailwind: {Tailwind, :install_and_run, [:demo, ~w(--watch)]}",
			"  ]"
		]);
	}

	public static function appJs(clientMode:Atom):String {
		if (clientMode == GENES)
			return joinLines([
				"import \"phoenix_html\"",
				"import {Socket} from \"phoenix\"",
				"import {LiveSocket} from \"phoenix_live_view\"",
				"",
				"let Hooks = {};",
				"const liveSocket = new LiveSocket(\"/live\", Socket, {hooks: Hooks})",
				"liveSocket.connect()"
			]);
		return joinLines([
			"import \"phoenix_html\"",
			"import {Socket} from \"phoenix\"",
			"import {LiveSocket} from \"phoenix_live_view\"",
			"import {hooks as colocatedHooks} from \"phoenix-colocated/demo\"",
			"",
			"const liveSocket = new LiveSocket(\"/live\", Socket, {",
			"  params: {_csrf_token: \"test\"},",
			"  hooks: {...colocatedHooks},",
			"})",
			"",
			"liveSocket.connect()"
		]);
	}

	public static function rootLayoutSource():String {
		return joinLines([
			"<!DOCTYPE html>",
			"<html lang=\"en\">",
			"  <head>",
			"    <meta charset=\"utf-8\" />",
			"    <script defer phx-track-static type=\"text/javascript\" src={~p\"/assets/app.js\"}></script>",
			"  </head>",
			"  <body>{@inner_content}</body>",
			"</html>"
		]);
	}

	public static function haxeRootLayoutSource():String {
		return joinLines([
			"package server.layouts;",
			"",
			"import phoenix.types.Assigns;",
			"",
			"@:component",
			"class Layouts {",
			"  @:component",
			"  public static function root(assigns:Assigns<{inner_content:String}>):String {",
			"    return <html lang=\"en\">",
			"      <head>",
			"        <script defer phx-track-static type=\"text/javascript\" src=\"/assets/phoenix_app.js\"></script>",
			"      </head>",
			"      <body>" + DOLLAR_SIGN + "{assigns.inner_content}</body>",
			"    </html>;",
			"  }",
			"}"
		]);
	}

	public static function liveReactMixExs():String {
		return joinLines([
			"defmodule LiveReact.MixProject do",
			"  use Mix.Project",
			"",
			"  def project, do: [app: :live_react, version: \"0.1.0\"]",
			"  def application, do: []",
			"end"
		]);
	}

	static function joinLines(lines:Array<String>):String {
		return Enum.join(lines, "\n") + "\n";
	}
}
