// Generated by Haxe 4.3.7
(function ($global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var MainMinimal = function() { };
MainMinimal.main = function() {
	var simple = function() {
		console.log("MainMinimal.hx:12:","hello");
		return Promise.resolve(null);
	};
	console.log("MainMinimal.hx:15:","Anonymous async function created successfully");
};
var haxe_Exception = function(message,previous,native) {
	Error.call(this,message);
	this.message = message;
	this.__previousException = previous;
	this.__nativeException = native != null ? native : this;
};
haxe_Exception.caught = function(value) {
	if(((value) instanceof haxe_Exception)) {
		return value;
	} else if(((value) instanceof Error)) {
		return new haxe_Exception(value.message,null,value);
	} else {
		return new haxe_ValueException(value,null,value);
	}
};
haxe_Exception.__super__ = Error;
haxe_Exception.prototype = $extend(Error.prototype,{
	unwrap: function() {
		return this.__nativeException;
	}
});
var haxe_ValueException = function(value,previous,native) {
	haxe_Exception.call(this,String(value),previous,native);
	this.value = value;
};
haxe_ValueException.__super__ = haxe_Exception;
haxe_ValueException.prototype = $extend(haxe_Exception.prototype,{
	unwrap: function() {
		return this.value;
	}
});
var haxe_iterators_ArrayIterator = function(array) {
	this.current = 0;
	this.array = array;
};
haxe_iterators_ArrayIterator.prototype = {
	hasNext: function() {
		return this.current < this.array.length;
	}
	,next: function() {
		return this.array[this.current++];
	}
};
var reflaxe_js_Async = function() { };
reflaxe_js_Async.resolve = function(value) {
	return Promise.resolve(value);
};
reflaxe_js_Async.reject = function(error) {
	return Promise.reject(error);
};
reflaxe_js_Async.delay = function(value,delayMs) {
	return new Promise(function(resolve,reject) {
		window.setTimeout(function() {
			resolve(value);
		},delayMs);
	});
};
reflaxe_js_Async.fromCallback = function(fn) {
	return new Promise(function(resolve,reject) {
		try {
			fn(resolve);
		} catch( _g ) {
			var error = haxe_Exception.caught(_g).unwrap();
			reject(error);
		}
	});
};
MainMinimal.main();
})({});
