package reflaxe.elixir.ast;

#if (macro || reflaxe_runtime)

import haxe.macro.Type;
import haxe.macro.Expr;
import haxe.macro.Context;
import reflaxe.elixir.ast.ElixirAST;
using reflaxe.helpers.TypedExprHelper;
using reflaxe.helpers.TypeHelper;
using StringTools;

/**
 * ElixirASTBuilder: TypedExpr to ElixirAST Converter (Analysis Phase)
 * 
 * WHY: Bridge between Haxe's TypedExpr and our ElixirAST representation
 * - Preserves all semantic information from Haxe's type system
 * - Enriches nodes with metadata for later transformation phases
 * - Separates AST construction from string generation
 * - Enables multiple transformation passes on strongly-typed structure
 * 
 * WHAT: Converts Haxe TypedExpr nodes to corresponding ElixirAST nodes
 * - Handles all expression types (literals, variables, operations, calls)
 * - Captures type information and source positions
 * - Detects patterns that need special handling (e.g., array operations)
 * - Maintains context through metadata enrichment
 * 
 * HOW: Recursive pattern matching on TypedExpr with metadata preservation
 * - Each TypedExpr constructor maps to one or more ElixirAST nodes
 * - Metadata carries context through the entire pipeline
 * - Complex expressions decomposed into simpler AST nodes
 * - Pattern detection integrated into conversion process
 * 
 * ARCHITECTURE BENEFITS:
 * - Single Responsibility: Only converts AST formats, no code generation
 * - Open/Closed: Easy to add new node types without modifying existing
 * - Testability: Can test AST conversion independently of generation
 * - Maintainability: Clear separation from transformation and printing
 * 
 * @see docs/03-compiler-development/INTERMEDIATE_AST_REFACTORING_PRD.md
 */
class ElixirASTBuilder {
    
    // Counter for generating unique loop function names
    static var loopCounter: Int = 0;
    
    // Map for renaming temporary underscore variables generated by Haxe
    // Key is the TVar.id (as String), value is the renamed variable name
    static var tempVarRenameMap: Map<String, String> = new Map();
    
    /**
     * Main entry point: Convert TypedExpr to ElixirAST
     * 
     * WHY: Single entry point for all AST conversion
     * WHAT: Recursively converts TypedExpr tree to ElixirAST tree
     * HOW: Pattern matches on expr type and delegates to specific handlers
     */
    public static function buildFromTypedExpr(expr: TypedExpr): ElixirAST {
        #if debug_ast_builder
        trace('[XRay AST Builder] Converting TypedExpr: ${expr.expr}');
        #end
        
        var metadata = createMetadata(expr);
        var astDef = convertExpression(expr);
        
        // Check if this is an enum constructor that needs idiomatic transformation
        switch(expr.expr) {
            case TCall(e, _) if (e != null && isEnumConstructor(e) && hasIdiomaticMetadata(e)):
                metadata.requiresIdiomaticTransform = true;
                metadata.idiomaticEnumType = getEnumTypeName(e);
                #if debug_ast_builder
                trace('[AST Builder] Marked AST for idiomatic transform: ${getEnumTypeName(e)}');
                #end
            default:
        }
        
        var result = makeASTWithMeta(astDef, metadata, expr.pos);
        
        #if debug_ast_builder
        trace('[XRay AST Builder] Generated AST: ${astDef}');
        #end
        
        return result;
    }
    
    /**
     * Convert TypedExprDef to ElixirASTDef
     */
    static function convertExpression(expr: TypedExpr): ElixirASTDef {
        return switch(expr.expr) {
            // ================================================================
            // Literals and Constants
            // ================================================================
            case TConst(TInt(i)):
                EInteger(i);
                
            case TConst(TFloat(f)):
                EFloat(Std.parseFloat(f));
                
            case TConst(TString(s)):
                EString(s);
                
            case TConst(TBool(b)):
                EBoolean(b);
                
            case TConst(TNull):
                ENil;
                
            case TConst(TThis):
                // In Elixir, 'this' refers to the first parameter of instance methods (usually 'struct')
                // This will be handled by the transformer or the function compiler
                // For now, use a placeholder that will be replaced
                EVar("struct");
                
            case TConst(TSuper):
                // Elixir doesn't have super - this needs special handling
                // Generally should not appear in valid code
                // For now, just return nil since super isn't supported in Elixir
                ENil;
                
            // ================================================================
            // Variables and Binding
            // ================================================================
            case TLocal(v):
                // Check if this is a renamed parameter (e.g., priority2 -> priority)
                var varName = v.name;
                
                // Always debug variables that might be renamed
                #if debug_ast_pipeline
                if (varName.indexOf("priority") >= 0 || varName.indexOf("_") >= 0 || ~/\d$/.match(varName)) {
                    trace('[AST Builder] TLocal variable: name="${varName}", id=${v.id}, pos=${expr.pos}');
                }
                #end
                
                // Handle Haxe-generated temp variables that start with underscore
                // These are variables like _g, _g1, etc. that Haxe generates during desugaring
                // In Elixir, underscore-prefixed variables should not be used after assignment
                // So we create a mapping to rename them consistently
                if (varName.charAt(0) == "_" && varName.length > 1) {
                    // Check if we already have a mapping for this variable ID
                    var idKey = Std.string(v.id);
                    if (!tempVarRenameMap.exists(idKey)) {
                        // Create a new non-underscore name for this temp variable
                        var newName = if (~/^_g\d*$/.match(varName)) {
                            // _g, _g1, _g2 -> g, g1, g2
                            varName.substr(1);
                        } else if (~/^_\d+$/.match(varName)) {
                            // _1, _2 -> temp1, temp2
                            "temp" + varName.substr(1);
                        } else {
                            // Other underscore variables - keep as is for now
                            varName;
                        };
                        tempVarRenameMap.set(idKey, newName);
                        #if debug_ast_pipeline
                        trace('[AST Builder] Registering temp var rename: ${varName} (id=${v.id}) -> ${newName}');
                        #end
                    }
                    varName = tempVarRenameMap.get(idKey);
                }
                // Handle collision-renamed variables (priority2 -> priority)
                else if (~/^(.+?)(\d+)$/.match(varName)) {
                    var regex = ~/^(.+?)(\d+)$/;
                    if (regex.match(varName)) {
                        var baseName = regex.matched(1);
                        var suffix = regex.matched(2);
                        
                        // Only strip suffix if it's a small number (1-9) which indicates collision renaming
                        // Don't strip from intentional names like "base64" or "sha256"
                        if (suffix.length == 1 && baseName != "_g") { // Don't modify _g1 style names here
                            #if debug_ast_pipeline  
                            trace('[AST Builder] Collision-renamed variable detected: ${varName} -> ${baseName}');
                            #end
                            varName = baseName;
                        }
                    }
                }
                
                EVar(toElixirVarName(varName));
                
            case TVar(v, init):
                // Apply same underscore variable renaming as in TLocal
                var varName = v.name;
                if (varName.charAt(0) == "_" && varName.length > 1) {
                    var idKey = Std.string(v.id);
                    if (!tempVarRenameMap.exists(idKey)) {
                        // Create a new non-underscore name for this temp variable
                        var newName = if (~/^_g\d*$/.match(varName)) {
                            // _g, _g1, _g2 -> g, g1, g2
                            varName.substr(1);
                        } else if (~/^_\d+$/.match(varName)) {
                            // _1, _2 -> temp1, temp2
                            "temp" + varName.substr(1);
                        } else {
                            // Other underscore variables - keep as is for now
                            varName;
                        };
                        tempVarRenameMap.set(idKey, newName);
                        #if debug_ast_pipeline
                        trace('[AST Builder] Registering temp var rename in TVar: ${varName} (id=${v.id}) -> ${newName}');
                        #end
                    }
                    varName = tempVarRenameMap.get(idKey);
                }
                
                if (init != null) {
                    EMatch(
                        PVar(toElixirVarName(varName)),
                        buildFromTypedExpr(init)
                    );
                } else {
                    // Uninitialized variable - use nil
                    EMatch(
                        PVar(toElixirVarName(varName)),
                        makeAST(ENil)
                    );
                }
                
            // ================================================================
            // Binary Operations
            // ================================================================
            case TBinop(op, e1, e2):
                var left = buildFromTypedExpr(e1);
                var right = buildFromTypedExpr(e2);
                
                switch(op) {
                    case OpAdd: EBinary(Add, left, right);
                    case OpSub: EBinary(Subtract, left, right);
                    case OpMult: EBinary(Multiply, left, right);
                    case OpDiv: EBinary(Divide, left, right);
                    case OpMod: EBinary(Remainder, left, right);
                    
                    case OpEq: EBinary(Equal, left, right);
                    case OpNotEq: EBinary(NotEqual, left, right);
                    case OpLt: EBinary(Less, left, right);
                    case OpLte: EBinary(LessEqual, left, right);
                    case OpGt: EBinary(Greater, left, right);
                    case OpGte: EBinary(GreaterEqual, left, right);
                    
                    case OpBoolAnd: EBinary(AndAlso, left, right);
                    case OpBoolOr: EBinary(OrElse, left, right);
                    
                    case OpAssign: EMatch(extractPattern(e1), right);
                    case OpAssignOp(op2): 
                        // a += b becomes a = a + b
                        var innerOp = convertAssignOp(op2);
                        EMatch(extractPattern(e1), makeAST(EBinary(innerOp, left, right)));
                    
                    case OpAnd: EBinary(BitwiseAnd, left, right);
                    case OpOr: EBinary(BitwiseOr, left, right);
                    case OpXor: EBinary(BitwiseXor, left, right);
                    case OpShl: EBinary(ShiftLeft, left, right);
                    case OpShr: EBinary(ShiftRight, left, right);
                    case OpUShr: EBinary(ShiftRight, left, right); // No unsigned in Elixir
                    
                    case OpInterval: ERange(left, right, false);
                    case OpArrow: EFn([{
                        args: [PVar("_arrow")], // Placeholder, will be transformed
                        body: right
                    }]);
                    case OpIn: EBinary(In, left, right);
                    case OpNullCoal: 
                        // a ?? b becomes if a != nil, do: a, else: b
                        EIf(
                            makeAST(EBinary(NotEqual, left, makeAST(ENil))),
                            left,
                            right
                        );
                }
                
            // ================================================================
            // Unary Operations
            // ================================================================
            case TUnop(op, postFix, e):
                var expr = buildFromTypedExpr(e).def;
                
                switch(op) {
                    case OpNot: EUnary(Not, makeAST(expr));
                    case OpNeg: EUnary(Negate, makeAST(expr));
                    case OpNegBits: EUnary(BitwiseNot, makeAST(expr));
                    case OpIncrement, OpDecrement:
                        // Elixir is immutable, so we convert increment/decrement to addition/subtraction
                        // Note: This doesn't handle the assignment side-effect, which needs to be handled in context
                        var one = makeAST(EInteger(1));
                        var value = makeAST(expr);
                        if (op == OpIncrement) {
                            EBinary(Add, value, one);
                        } else {
                            EBinary(Subtract, value, one);
                        };
                    case OpSpread:
                        // Spread operator for destructuring
                        EUnquoteSplicing(makeAST(expr));
                }
                
            // ================================================================
            // Function Calls
            // ================================================================
            case TCall(e, el):
                // Check if this is an enum constructor call first
                if (e != null && isEnumConstructor(e)) {
                    // Enum constructor call - generate tuple syntax {:tag, arg1, arg2, ...}
                    var tag = extractEnumTag(e);
                    var args = [for (arg in el) buildFromTypedExpr(arg)];
                    
                    // Create the tuple - metadata will be added at buildFromTypedExpr level
                    ETuple([makeAST(EAtom(tag))].concat(args));
                } else {
                    // Regular function call
                    var target = e != null ? buildFromTypedExpr(e) : null;
                    var args = [for (arg in el) buildFromTypedExpr(arg)];
                    
                    // Detect special call patterns
                    switch(e.expr) {
                        case TField(obj, fa):
                            var fieldName = extractFieldName(fa);
                            var objAst = buildFromTypedExpr(obj);
                            
                            // Check for module calls
                            if (isModuleCall(obj)) {
                                // Convert method name to snake_case for Elixir
                                var elixirFuncName = toSnakeCase(fieldName);
                                ERemoteCall(objAst, elixirFuncName, args);
                            } else {
                                // Check for array/list concatenation
                                if (fieldName == "concat" && isArrayType(obj.t)) {
                                    // Convert array.concat(other) to array ++ other in Elixir
                                    if (args.length == 1) {
                                        EBinary(Concat, objAst, args[0]);
                                    } else {
                                        // Fallback for invalid concat calls
                                        ECall(objAst, fieldName, args);
                                    }
                                } 
                                // Check for Map operations that need transformation
                                else if (isMapType(obj.t)) {
                                    // Transform Map methods to Elixir Map module functions
                                    switch(fieldName) {
                                        case "set" if (args.length == 2):
                                            // map.set(key, value) → Map.put(map, key, value)
                                            ERemoteCall(makeAST(EVar("Map")), "put", [objAst].concat(args));
                                        case "get" if (args.length == 1):
                                            // map.get(key) → Map.get(map, key)
                                            ERemoteCall(makeAST(EVar("Map")), "get", [objAst].concat(args));
                                        case "remove" if (args.length == 1):
                                            // map.remove(key) → Map.delete(map, key)
                                            ERemoteCall(makeAST(EVar("Map")), "delete", [objAst].concat(args));
                                        case "exists" if (args.length == 1):
                                            // map.exists(key) → Map.has_key?(map, key)
                                            ERemoteCall(makeAST(EVar("Map")), "has_key?", [objAst].concat(args));
                                        case "keys" if (args.length == 0):
                                            // map.keys() → Map.keys(map)
                                            ERemoteCall(makeAST(EVar("Map")), "keys", [objAst]);
                                        case "values" if (args.length == 0):
                                            // map.values() → Map.values(map)
                                            ERemoteCall(makeAST(EVar("Map")), "values", [objAst]);
                                        default:
                                            // Fallback for other Map methods
                                            ECall(objAst, fieldName, args);
                                    }
                                } else {
                                    // Instance method call
                                    ECall(objAst, fieldName, args);
                                }
                            }
                        case TLocal(v):
                            // Check if this is a function variable (needs .() syntax in Elixir)
                            // Function variables in Elixir require .() syntax for invocation
                            var isFunctionVar = switch(v.t) {
                                case TFun(_, _): true;
                                case TAbstract(t, _):
                                    var abs = t.get();
                                    abs.name == "Function" || abs.name == "Fn";
                                default: false;
                            };
                            
                            if (isFunctionVar) {
                                // Function variable call - needs special handling for .() syntax
                                // We'll create a special marker that the printer will recognize
                                ECall(makeAST(EVar(toElixirVarName(v.name))), "", args);
                            } else {
                                // Regular local function call
                                ECall(null, toElixirVarName(v.name), args);
                            }
                        default:
                            if (target != null) {
                                // Complex target expression
                                ECall(target, "call", args);
                            } else {
                                // Should not happen
                                ECall(null, "unknown_call", args);
                            }
                    }
                }
                
            // ================================================================
            // Field Access
            // ================================================================
            case TField(e, fa):
                // Check for enum constructor references
                switch(fa) {
                    case FEnum(enumType, ef):
                        // Enum constructor reference (no arguments)
                        // Keep original Haxe name - snake_case conversion happens at print time
                        EAtom(ef.name);
                    default:
                        // Regular field access
                        var target = buildFromTypedExpr(e);
                        var fieldName = extractFieldName(fa);
                        
                        // Detect map/struct access patterns
                        if (isMapAccess(e.t)) {
                            EAccess(target, makeAST(EAtom(fieldName)));
                        } else {
                            EField(target, fieldName);
                        }
                }
                
            // ================================================================
            // Array Operations
            // ================================================================
            case TArrayDecl(el):
                var elements = [for (e in el) buildFromTypedExpr(e)];
                EList(elements);
                
            case TArray(e, index):
                var target = buildFromTypedExpr(e);
                var key = buildFromTypedExpr(index);
                EAccess(target, key);
                
            // ================================================================
            // Control Flow (Basic)
            // ================================================================
            case TIf(econd, eif, eelse):
                var condition = buildFromTypedExpr(econd);
                var thenBranch = buildFromTypedExpr(eif);
                var elseBranch = eelse != null ? buildFromTypedExpr(eelse) : null;
                EIf(condition, thenBranch, elseBranch);
                
            case TBlock(el):
                var expressions = [for (e in el) buildFromTypedExpr(e)];
                EBlock(expressions);
                
            case TReturn(e):
                if (e != null) {
                    buildFromTypedExpr(e).def; // Return value is implicit in Elixir
                } else {
                    ENil; // Explicit nil return
                }
                
            case TBreak:
                EThrow(makeAST(EAtom("break"))); // Will be transformed
                
            case TContinue:
                EThrow(makeAST(EAtom("continue"))); // Will be transformed
                
            // ================================================================
            // Pattern Matching (Switch/Case)
            // ================================================================
            case TSwitch(e, cases, edef):
                var expr = buildFromTypedExpr(e).def;
                var clauses = [];
                
                // Check if this is a topic_to_string-style temp variable switch
                // These need special handling for return context
                var needsTempVar = false;
                var tempVarName = "temp_result";
                
                // Detect if switch is in return context
                var isReturnContext = false; // TODO: Will be set via metadata
                
                for (c in cases) {
                    var patterns = [for (v in c.values) convertPattern(v)];
                    var body = buildFromTypedExpr(c.expr);
                    
                    // Multiple patterns become multiple clauses
                    for (pattern in patterns) {
                        clauses.push({
                            pattern: pattern,
                            guard: null, // Guards will be added in transformation
                            body: body
                        });
                    }
                }
                
                // Default case
                if (edef != null) {
                    clauses.push({
                        pattern: PWildcard,
                        guard: null,
                        body: buildFromTypedExpr(edef)
                    });
                }
                
                // Create the case expression
                var caseASTDef = ECase(makeAST(expr), clauses);
                
                // If in return context and needs temp var, wrap in assignment
                if (isReturnContext && needsTempVar) {
                    EBlock([
                        makeAST(EMatch(PVar(tempVarName), makeAST(caseASTDef))),
                        makeAST(EVar(tempVarName))
                    ]);
                } else {
                    caseASTDef;
                }
                
            // ================================================================
            // Try/Catch
            // ================================================================
            case TTry(e, catches):
                var body = buildFromTypedExpr(e);
                var rescueClauses = [];
                
                for (c in catches) {
                    var pattern = PVar(toElixirVarName(c.v.name));
                    var catchBody = buildFromTypedExpr(c.expr);
                    
                    rescueClauses.push({
                        pattern: pattern,
                        body: catchBody
                    });
                }
                
                ETry(body, rescueClauses, [], null, null);
                
            // ================================================================
            // Lambda/Anonymous Functions
            // ================================================================
            case TFunction(f):
                var args = [for (arg in f.args) PVar(toElixirVarName(arg.v.name))];
                var body = buildFromTypedExpr(f.expr);
                
                EFn([{
                    args: args,
                    guard: null,
                    body: body
                }]);
                
            // ================================================================
            // Object/Anonymous Structure
            // ================================================================
            case TObjectDecl(fields):
                var pairs = [];
                for (field in fields) {
                    var key = makeAST(EAtom(field.name));
                    var value = buildFromTypedExpr(field.expr);
                    pairs.push({key: key, value: value});
                }
                EMap(pairs);
                
            // ================================================================
            // Type Operations
            // ================================================================
            case TTypeExpr(m):
                // Check if this is an extern class with @:native annotation
                var moduleName = moduleTypeToString(m);
                
                // Check if this module has @:native metadata indicating it's an Elixir module
                var isNativeModule = switch(m) {
                    case TClassDecl(c):
                        var cl = c.get();
                        // Check if it's an extern class with @:native
                        if (cl.isExtern && cl.meta.has(":native")) {
                            // Get the native name from metadata
                            var nativeMeta = cl.meta.extract(":native");
                            if (nativeMeta.length > 0 && nativeMeta[0].params != null && nativeMeta[0].params.length > 0) {
                                switch(nativeMeta[0].params[0].expr) {
                                    case EConst(CString(s, _)):
                                        moduleName = s;
                                        true;
                                    default:
                                        false;
                                }
                            } else {
                                false;
                            }
                        } else {
                            false;
                        }
                    default:
                        false;
                };
                
                // Module references should always be EVar (no colon prefix)
                // This applies to both native Elixir modules and compiled Haxe classes
                EVar(moduleName);  // Module references are just capitalized identifiers
                
            case TCast(e, m):
                // Casts are mostly compile-time in Haxe
                buildFromTypedExpr(e).def;
                
            case TParenthesis(e):
                EParen(buildFromTypedExpr(e));
                
            case TMeta(m, e):
                // Metadata wrapping - preserve the expression
                buildFromTypedExpr(e).def;
                
            // ================================================================
            // Special Cases
            // ================================================================
            case TNew(c, _, el):
                // Constructor call becomes struct creation
                var className = c.get().name;
                var args = [for (e in el) buildFromTypedExpr(e)];
                
                // Check if this is a Map type (StringMap, IntMap, etc.)
                // Maps should generate regular Elixir maps %{}, not structs
                if (className == "StringMap" || className == "Map" || className.endsWith("Map")) {
                    // Generate empty map for Map constructors
                    EMap([]);
                } else {
                    // Will be transformed to proper struct syntax
                    EStruct(className, []);
                }
                
            case TFor(v, e1, e2):
                // For loop becomes comprehension
                var pattern = PVar(toElixirVarName(v.name));
                var expr = buildFromTypedExpr(e1);
                var body = buildFromTypedExpr(e2);
                
                EFor([{pattern: pattern, expr: expr}], [], body, null, false);
                
            case TWhile(econd, e, normalWhile):
                // While loops compile to recursive functions
                // We need to generate them inline since Elixir doesn't have while loops
                
                var condition = buildFromTypedExpr(econd);
                var body = buildFromTypedExpr(e);
                
                // For now, just create a call that will be handled by the transformer
                // The transformer's comprehensionConversionPass will convert this
                ECall(null, "while_loop", [condition, body]);
                
            case TThrow(e):
                EThrow(buildFromTypedExpr(e));
                
            case TEnumParameter(e, ef, index):
                // Enum field access
                var exprAST = buildFromTypedExpr(e);
                var field = ef.name;
                
                // Will be transformed to proper pattern extraction
                ECall(exprAST, "elem", [makeAST(EInteger(index + 1))]); // +1 for tag
                
            case TEnumIndex(e):
                // Get enum tag index
                var exprAST = buildFromTypedExpr(e);
                ECall(exprAST, "elem", [makeAST(EInteger(0))]);
                
            case TIdent(s):
                // Identifier reference
                EVar(toElixirVarName(s));
        }
    }
    
    /**
     * Create metadata from TypedExpr
     */
    static function createMetadata(expr: TypedExpr): ElixirMetadata {
        return {
            sourceExpr: expr,
            sourceLine: expr.pos != null ? Context.getPosInfos(expr.pos).min : 0,
            sourceFile: expr.pos != null ? Context.getPosInfos(expr.pos).file : null,
            type: expr.t,
            elixirType: typeToElixir(expr.t),
            purity: isPure(expr),
            tailPosition: false, // Will be set by transformer
            async: false, // Will be detected by transformer
            requiresReturn: false, // Will be set by context
            requiresTempVar: false, // Will be set by transformer
            inPipeline: false, // Will be set by transformer
            inComprehension: false, // Will be set by context
            inGuard: false, // Will be set by context
            canInline: canBeInlined(expr),
            isConstant: isConstant(expr),
            sideEffects: hasSideEffects(expr)
        };
    }
    
    /**
     * Convert Haxe values to patterns
     * 
     * WHY: Switch case values need to be converted to Elixir patterns
     * WHAT: Handles literals, enum constructors, variables, and complex patterns
     * HOW: Analyzes the TypedExpr structure and generates appropriate pattern
     */
    static function convertPattern(value: TypedExpr): EPattern {
        return switch(value.expr) {
            // Literals
            case TConst(TInt(i)): 
                PLiteral(makeAST(EInteger(i)));
            case TConst(TFloat(f)): 
                PLiteral(makeAST(EFloat(Std.parseFloat(f))));
            case TConst(TString(s)): 
                PLiteral(makeAST(EString(s)));
            case TConst(TBool(b)): 
                PLiteral(makeAST(EBoolean(b)));
            case TConst(TNull): 
                PLiteral(makeAST(ENil));
                
            // Variables (for pattern matching)
            case TLocal(v):
                PVar(toElixirVarName(v.name));
                
            // Enum constructors
            case TEnumParameter(e, ef, index):
                // This represents matching against enum constructor arguments
                // We'll need to handle this in the context of the full pattern
                PVar("_enum_param_" + index);
                
            case TEnumIndex(e):
                // Matching against enum index (for switch on elem(tuple, 0))
                PLiteral(makeAST(EInteger(0))); // Will be refined based on actual enum
                
            // Array patterns
            case TArrayDecl(el):
                PList([for (e in el) convertPattern(e)]);
                
            // Tuple patterns (for enum matching)
            case TCall(e, el) if (isEnumConstructor(e)):
                // Enum constructor pattern
                var tag = extractEnumTag(e);
                var args = [for (arg in el) convertPattern(arg)];
                // Create tuple pattern {:tag, arg1, arg2, ...}
                // Keep original name - conversion happens at print time
                PTuple([PLiteral(makeAST(EAtom(tag)))].concat(args));
                
            // Field access (for enum constructors)
            case TField(e, FEnum(_, ef)):
                // Direct enum constructor reference
                if (ef.params.length == 0) {
                    // No-argument constructor
                    // Keep original name - conversion happens at print time
                    PLiteral(makeAST(EAtom(ef.name)));
                } else {
                    // Constructor with arguments - needs to be a tuple pattern
                    // This will be {:Constructor, _, _, ...} with wildcards for args
                    var wildcards = [for (i in 0...ef.params.length) PWildcard];
                    // Keep original name - conversion happens at print time
                    PTuple([PLiteral(makeAST(EAtom(ef.name)))].concat(wildcards));
                }
                
            // Default/wildcard
            default: 
                PWildcard;
        }
    }
    
    /**
     * Check if an expression is an enum constructor call
     */
    static function isEnumConstructor(expr: TypedExpr): Bool {
        return switch(expr.expr) {
            case TField(_, FEnum(_, _)): true;
            default: false;
        }
    }
    
    /**
     * Check if an enum has @:elixirIdiomatic metadata
     */
    static function hasIdiomaticMetadata(expr: TypedExpr): Bool {
        return switch(expr.expr) {
            case TField(_, FEnum(enumRef, _)):
                var enumType = enumRef.get();
                var hasIt = enumType.meta.has(":elixirIdiomatic");
                #if debug_ast_builder
                trace('[AST Builder] Checking @:elixirIdiomatic for ${enumType.name}: $hasIt');
                #end
                hasIt;
            default: false;
        }
    }
    
    /**
     * Get the enum type name for pattern detection
     */
    static function getEnumTypeName(expr: TypedExpr): String {
        return switch(expr.expr) {
            case TField(_, FEnum(enumRef, _)):
                var enumType = enumRef.get();
                enumType.name;
            default: "";
        }
    }
    
    /**
     * Convert Haxe identifier to Elixir atom name
     * 
     * GENERAL RULE: When Haxe identifiers become Elixir atoms,
     * they should follow Elixir naming conventions (snake_case).
     * This ensures generated code looks idiomatic.
     * 
     * Examples:
     * - OneForOne → one_for_one
     * - RestForOne → rest_for_one
     * - SimpleOneForOne → simple_one_for_one
     */
    static function toElixirAtomName(name: String): String {
        var result = [];
        for (i in 0...name.length) {
            var c = name.charAt(i);
            if (i > 0 && c == c.toUpperCase() && c != c.toLowerCase()) {
                result.push("_");
                result.push(c.toLowerCase());
            } else {
                result.push(c.toLowerCase());
            }
        }
        return result.join("");
    }
    
    /**
     * Check if type is an array type
     */
    static function isArrayType(t: Type): Bool {
        return switch(t) {
            case TInst(c, _):
                var cl = c.get();
                cl.name == "Array";
            case TAbstract(a, _):
                var abs = a.get();
                abs.name == "Array";
            default: false;
        }
    }
    
    /**
     * Check if type is a Map type
     */
    static function isMapType(t: Type): Bool {
        return switch(t) {
            case TInst(c, _):
                var cl = c.get();
                cl.name == "StringMap" || cl.name == "IntMap" || cl.name == "ObjectMap" || 
                cl.name == "Map" || cl.name.endsWith("Map");
            case TAbstract(a, params):
                var abs = a.get();
                abs.name == "Map" || abs.name.endsWith("Map");
            default: false;
        }
    }
    
    /**
     * Extract enum constructor tag name
     */
    static function extractEnumTag(expr: TypedExpr): String {
        return switch(expr.expr) {
            case TField(_, FEnum(_, ef)): ef.name;
            default: "unknown";
        }
    }
    
    /**
     * Extract pattern from left-hand side expression
     */
    static function extractPattern(expr: TypedExpr): EPattern {
        return switch(expr.expr) {
            case TLocal(v): PVar(toElixirVarName(v.name));
            case TField(e, fa): 
                // Map/struct field pattern
                PVar(extractFieldName(fa));
            default: PWildcard;
        }
    }
    
    /**
     * Convert assignment operator to binary operator
     */
    static function convertAssignOp(op: Binop): EBinaryOp {
        return switch(op) {
            case OpAdd: Add;
            case OpSub: Subtract;
            case OpMult: Multiply;
            case OpDiv: Divide;
            case OpMod: Remainder;
            case OpAnd: BitwiseAnd;
            case OpOr: BitwiseOr;
            case OpXor: BitwiseXor;
            case OpShl: ShiftLeft;
            case OpShr: ShiftRight;
            default: Add; // Fallback
        }
    }
    
    /**
     * Convert variable name to Elixir convention
     * Preserves special Elixir constants like __MODULE__, __FILE__, __ENV__
     */
    static function toElixirVarName(name: String): String {
        // Special Elixir constants should be preserved
        var specialConstants = ["__MODULE__", "__FILE__", "__ENV__", "__DIR__", "__CALLER__"];
        if (specialConstants.indexOf(name) >= 0) {
            return name;
        }
        
        // Simple snake_case conversion for regular variables
        var result = "";
        for (i in 0...name.length) {
            var char = name.charAt(i);
            if (i > 0 && char == char.toUpperCase() && char != "_") {
                result += "_" + char.toLowerCase();
            } else {
                result += char.toLowerCase();
            }
        }
        return result;
    }
    
    /**
     * Extract field name from FieldAccess
     */
    static function extractFieldName(fa: FieldAccess): String {
        return switch(fa) {
            case FInstance(_, _, cf) | FStatic(_, cf) | FAnon(cf) | FClosure(_, cf):
                cf.get().name;
            case FDynamic(s):
                s;
            case FEnum(_, ef):
                ef.name;
        }
    }
    
    /**
     * Convert camelCase to snake_case
     */
    static function toSnakeCase(s: String): String {
        // Handle empty string
        if (s.length == 0) return s;
        
        var result = new StringBuf();
        for (i in 0...s.length) {
            var char = s.charAt(i);
            if (i > 0 && char == char.toUpperCase() && char != char.toLowerCase()) {
                // Insert underscore before uppercase letter (except at start)
                result.add("_");
                result.add(char.toLowerCase());
            } else {
                result.add(char.toLowerCase());
            }
        }
        return result.toString();
    }
    
    /**
     * Check if expression is a module call
     */
    static function isModuleCall(expr: TypedExpr): Bool {
        return switch(expr.expr) {
            case TTypeExpr(_): true;
            default: false;
        }
    }
    
    /**
     * Check if type represents a map/struct
     */
    static function isMapAccess(t: Type): Bool {
        return switch(t) {
            case TAnonymous(_): true;
            case TInst(_.get() => ct, _): ct.isInterface || ct.name.endsWith("Map");
            default: false;
        }
    }
    
    /**
     * Convert module type to string
     */
    static function moduleTypeToString(m: ModuleType): String {
        return switch(m) {
            case TClassDecl(c): c.get().name;
            case TEnumDecl(e): e.get().name;
            case TTypeDecl(t): t.get().name;
            case TAbstract(a): a.get().name;
        }
    }
    
    /**
     * Convert Haxe type to Elixir type string
     */
    static function typeToElixir(t: Type): String {
        return switch(t) {
            case TInst(_.get() => {name: "String"}, _): "binary";
            case TInst(_.get() => {name: "Array"}, _): "list";
            case TAbstract(_.get() => {name: "Int"}, _): "integer";
            case TAbstract(_.get() => {name: "Float"}, _): "float";
            case TAbstract(_.get() => {name: "Bool"}, _): "boolean";
            case TDynamic(_): "any";
            default: "term";
        }
    }
    
    /**
     * Check if expression is pure (no side effects)
     */
    static function isPure(expr: TypedExpr): Bool {
        return switch(expr.expr) {
            case TConst(_) | TLocal(_) | TTypeExpr(_): true;
            case TBinop(_, e1, e2): isPure(e1) && isPure(e2);
            case TUnop(_, _, e): isPure(e);
            case TField(e, _): isPure(e);
            case TParenthesis(e): isPure(e);
            default: false;
        }
    }
    
    /**
     * Check if expression can be inlined
     */
    static function canBeInlined(expr: TypedExpr): Bool {
        return switch(expr.expr) {
            case TConst(_) | TLocal(_): true;
            case TBinop(_, e1, e2): canBeInlined(e1) && canBeInlined(e2);
            case TUnop(_, _, e): canBeInlined(e);
            default: false;
        }
    }
    
    /**
     * Check if expression is constant
     */
    static function isConstant(expr: TypedExpr): Bool {
        return switch(expr.expr) {
            case TConst(_): true;
            default: false;
        }
    }
    
    /**
     * Check if expression has side effects
     */
    static function hasSideEffects(expr: TypedExpr): Bool {
        return switch(expr.expr) {
            case TCall(_, _) | TNew(_, _, _) | TVar(_, _): true;
            case TBinop(OpAssign | OpAssignOp(_), _, _): true;
            case TUnop(OpIncrement | OpDecrement, _, _): true;
            case TThrow(_): true;
            default: false;
        }
    }
}

#end