/* @generated by mix haxe.phoenix.live_react; do not edit */

import {SignalConsoleBoundary as SignalConsoleComponent} from "./signal-console-boundary"

export const componentRegistry = {

  SignalConsole: SignalConsoleComponent,

} as const

export type ComponentName = keyof typeof componentRegistry

export default componentRegistry
