/* Generated by PhoenixHx LiveReactEventProtocol. Do not edit. */
export const LIVE_EVENT_PROTOCOL_HASH = "e9ea4ff291d073e3a877c602cda71d08801ced07" as const
export const LIVE_EVENT_PROTOCOL_MANIFEST = "protocol phoenixhx_live_react_hx.live.SignalConsoleEvent\ncompanion SignalConsoleEvents\nevent hook Pulse signal_pulse (payload:phoenixhx_live_react_hx.live.SignalPulseInput{channel:String->channel:string})\n" as const

/** Structural subset accepted by stock LiveReact's broader pushEvent function. */
export type LiveReactPushEvent = (
  event: string,
  payload: Record<string, unknown>,
) => unknown

const hasOwn = (value: Record<string, unknown>, key: string): boolean =>
  Object.prototype.hasOwnProperty.call(value, key)

function expectRecord(value: unknown, label: string): Record<string, unknown> {
  if (value === null || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(label + " must be an object")
  }
  return value as Record<string, unknown>
}

function expectExactKeys(
  value: Record<string, unknown>,
  required: readonly string[],
  optional: readonly string[],
  label: string,
): void {
  const allowed = new Set([...required, ...optional])
  for (const key of Object.keys(value)) {
    if (!allowed.has(key)) {
      throw new Error(label + " has unexpected field " + key)
    }
  }
  for (const key of required) {
    if (!hasOwn(value, key)) {
      throw new Error(label + " is missing field " + key)
    }
  }
}

function expectString(value: unknown, label: string): string {
  if (typeof value !== "string") {
    throw new Error(label + " must be a string")
  }
  return value
}

export const PULSE_EVENT = "signal_pulse" as const
export interface PulseInput {
  readonly channel: string
}

export function decodePulseInput(value: unknown): PulseInput {
  const input = expectRecord(value, "phoenixhx_live_react_hx.live.SignalConsoleEvent.Pulse")
  expectExactKeys(
    input,
    ["channel"],
    [],
    "phoenixhx_live_react_hx.live.SignalConsoleEvent.Pulse",
  )
  return {
    channel: expectString(input["channel"], "phoenixhx_live_react_hx.live.SignalConsoleEvent.Pulse.channel"),
  }
}

export function encodePulsePayload(input: PulseInput): Record<string, unknown> {
  return {
    channel: input.channel,
  }
}

export function pushPulse(pushEvent: LiveReactPushEvent, candidate: PulseInput): void {
  const input = decodePulseInput(candidate)
  pushEvent(PULSE_EVENT, encodePulsePayload(input))
}
