package phoenix;

/**
 * PresenceBehavior: Type-safe interface for Phoenix.Presence modules
 * 
 * ## Overview
 * 
 * This interface provides a type-safe way to implement Phoenix.Presence modules in Haxe.
 * Classes that implement this interface automatically get both internal and external
 * APIs generated at compile-time through the @:autoBuild macro.
 * 
 * ## Usage Pattern
 * 
 * ```haxe
 * @:native("MyAppWeb.Presence")
 * class MyPresence implements PresenceBehavior {
 *     // The macro automatically generates:
 *     // - Internal methods: trackInternal, updateInternal, untrackInternal (with self())
 *     // - External static methods: track, update, untrack (without self())
 *     // - Utility methods: list, getByKey
 * }
 * ```
 * 
 * ## Generated Methods
 * 
 * ### Internal Methods (for use within the presence module)
 * - `trackInternal(socket, key, meta)` → `track(self(), socket, key, meta)`
 * - `updateInternal(socket, key, meta)` → `update(self(), socket, key, meta)`
 * - `untrackInternal(socket, key, meta)` → `untrack(self(), socket, key, meta)`
 * 
 * ### External Static Methods (for use from LiveViews)
 * - `track(socket, key, meta)` → Calls Phoenix.Presence.track externally
 * - `update(socket, key, meta)` → Calls Phoenix.Presence.update externally
 * - `untrack(socket, key)` → Calls Phoenix.Presence.untrack externally
 * 
 * ### Utility Methods (available in both contexts)
 * - `list(socket)` → Returns current presences
 * - `getByKey(socket, key)` → Returns specific presence entry
 * 
 * ## Type Safety Benefits
 * 
 * 1. **Compile-time validation** of presence metadata structure
 * 2. **IntelliSense support** for all presence operations
 * 3. **No runtime errors** from missing self() injection
 * 4. **Consistent API** across all presence modules
 * 
 * ## Implementation Details
 * 
 * The @:autoBuild macro (PresenceMacro.build()) handles:
 * - Detecting whether code is inside or outside the presence module
 * - Generating appropriate method signatures
 * - Injecting self() for internal operations
 * - Preserving type safety throughout
 * 
 * ## Phoenix.Presence Behavior
 * 
 * When a module uses `use Phoenix.Presence`, it:
 * 1. Adds the Phoenix.Presence behavior to the module
 * 2. Injects track/4, update/4, untrack/3 functions that expect self() as first arg
 * 3. Provides list/1 and get_by_key/2 utility functions
 * 
 * This Haxe interface replicates that pattern with compile-time safety.
 * 
 * @see phoenix.macros.PresenceMacro - The build macro implementation
 * @see phoenix.Presence - The Phoenix.Presence extern for external usage
 * @see docs/05-architecture/PHOENIX_PRESENCE_BEHAVIOR_PATTERNS.md - Architecture docs
 */
@:autoBuild(phoenix.macros.PresenceMacro.build())
interface PresenceBehavior {
    // Interface is empty - all methods are generated by the macro
    // This follows the same pattern as other Haxe interfaces with @:autoBuild
}