Code.require_file("user_queries.ex", __DIR__)
Code.require_file("user_changeset.ex", __DIR__)
Code.require_file("std.ex", __DIR__)
Code.require_file("repo.ex", __DIR__)
Code.require_file("haxe/log.ex", __DIR__)
Code.require_file("create_users_table.ex", __DIR__)
Code.require_file("accounts.ex", __DIR__)
Code.require_file("ecto_integration_simple.ex", __DIR__)
EctoIntegrationSimple.main()