/* @generated by mix haxe.phoenix.live_react; do not edit */

import {TodoInsightsBoundary as TodoInsightsComponent} from "./generated/todo_insights/TodoInsightsIsland"

export const componentRegistry = {

  TodoInsights: TodoInsightsComponent,

} as const

export type ComponentName = keyof typeof componentRegistry

export default componentRegistry
