import Config

disable_watchers = System.get_env("DISABLE_WATCHERS") == "1"

dev_port =
  case System.get_env("PORT") do
    nil ->
      4000

    val ->
      case Integer.parse(val) do
        {int, _} -> int
        :error -> 4000
      end
  end

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :phoenix_hx_todo, PhoenixHxTodoWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: dev_port],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "Kv4ECMYMPL2dz3dyI7p5pVRI5naAtIhZMZNsA4nf+/EekEpff8e6LX3W7cyuxVi8",
  watchers:
    (if disable_watchers do
       []
     else
       [

    # BEGIN reflaxe_elixir haxe_client
    # Haxe client JS build:
    # - Compiles to assets/js/_hx_app_tmp.js (temp output Haxe may delete during rebuilds).
    # - Promotes to assets/js/hx_app.js (stable import path for esbuild --watch).
    haxe_client: [
      "mix",
      "haxe.watch",
      "--hxml",
      "build-client.hxml",
      "--dirs",
      "src_haxe",
      "--debounce",
      "150",
      "--promote",
      "assets/js/_hx_app_tmp.js:assets/js/hx_app.js,assets/js/_hx_app_tmp.js.map:assets/js/hx_app.js.map",
      cd: Path.expand("../", __DIR__)
    ],
    # END reflaxe_elixir haxe_client

    esbuild: {Esbuild, :install_and_run, [:phoenix_hx_todo, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:phoenix_hx_todo, ~w(--watch)]}
       ]
     end)

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :phoenix_hx_todo, PhoenixHxTodoWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/phoenix_hx_todo_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :phoenix_hx_todo, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
