package phoenix.types;

import elixir.types.Atom;

/**
 * Typed LiveView assign key token.
 *
 * WHAT
 * - Models a Phoenix assign key as a typed token: `AssignKey<TAssigns, TValue>`.
 *
 * WHY
 * - `LiveSocket.assign(_.field, value)` used macro `Expr` arguments, which are not typed
 *   call-site values for IDE completion purposes.
 * - A typed key token gives Haxe's normal typer enough information to provide key completion
 *   and to enforce that value/updater/default function types match the selected key.
 *
 * HOW
 * - Runtime representation is still an `Atom` (zero runtime overhead).
 * - The type parameters are phantom markers used only by the type checker.
 * - Key constants are generated by `@:build(phoenix.macros.AssignKeysBuilder.build(...))`
 *   and cast from atom literals.
 *
 * EXAMPLES
 * Haxe:
 *   socket.assignKey(CounterAssignKeys.count, 0);
 *   socket.updateKey(CounterAssignKeys.count, (n) -> n + 1);
 *
 * Elixir:
 *   assign(socket, :count, 0)
 *   update(socket, :count, &(&1 + 1))
 */
abstract AssignKey<TAssigns, TValue>(Atom) to Atom {}
